### ISSUE TITLE
csl-corrections initialized

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-corrections#1]
This csl-corrections repository aims to contain the data and code relating to user submitted corrections to the dictionaries of the Cologne sanskrit lexicon.

[README-init](https://github.com/sanskrit-lexicon/csl-corrections/blob/master/README-init.md) describes the initialization.

Also, an .htaccess rewrite statement on the Cologne server (in the php directory) causes the
code to be run from this repository:
```Redirect 302 "/php/correction_form.php" "https://www.sanskrit-lexicon.uni-koeln.de/scans/csl-corrections/app/correction_form.php"```

Thus, when a user clicks a `corrections` link, the url will be in this repository at Cologne:
![image](https://user-images.githubusercontent.com/6393033/70958773-3ceb2900-2048-11ea-9117-8c2a8abdacd8.png)

**Comment by funderburkjim** [comment]
The [CORRECTIONS](https://github.com/sanskrit-lexicon/CORRECTIONS) repository has not been
changed, but will no longer be part of the processing of user-submitted corrections.

Similarly, the files and programs in the /php directory of the Cologne server pertaining to the correction forms will no longer be used.

**Comment by funderburkjim** [comment]
## enhancement ideas

* Document how to process user-submitted corrections.
* Automate the updates to this git repository. 
  * develop a cron job on the Cologne server for this.  @drdhaval2785 maybe can do this,
    as he has experience with git and cron jobs. The cron job might 
     * 'git add', 'git commit' and 'git push'.   
     * generate emails to those responsible for updating the csl-orig digitizations based on the
        user submitted corrections
* develop a process to notify people with local installations when csl-orig changes have been made,
   so such local installations can be kept up to date.

**Comment by drdhaval2785** [comment]
@funderburkjim 
I tried to set up a cronjob at Cologne server.
The response was that I am not authorised to use crontab.
There must be some access control to crontab in the Cologne servers because it can affect other users too.
So, we have to think about different plan I guess.

**Comment by gasyoun** [comment]
> So, we have to think about different plan I guess.

Plan is fine. More admin rights should be granted, guess it's possible.

**Comment by drdhaval2785** [comment]
requested webmaster for crontab access.

**Comment by gasyoun** [comment]
> Thus, when a user clicks a corrections link, the url will be in this repository at Cologne:

As said before, I would hide this link. This is very uneasy way. We should hide the ID. The updated correction submission form should be used.

> Similarly, the files and programs in the /php directory of the Cologne server pertaining to the correction forms will no longer be used.

Hurray. Move the the /old folder?

**Comment by gasyoun** [comment]
> requested webmaster for crontab access.

Received, @drdhaval2785 ?
