### ISSUE TITLE
Find English errors

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/csl-corrections#14]
Based on an error report aky->sky, I thought that there may be multiple such English errors in our dictionaries. I am trying to write a script to find out the potentially erroneous words and their suggested resolutions.

Following is a sample from MD.

Each line is having the following structure
`lnum:headword:commaSeparatedError`

EDIT -
as on 01 Jan 2021, the error files are now stored at https://github.com/sanskrit-lexicon/CORRECTIONS/tree/master/english_error/output

**Comment by drdhaval2785** [comment]
Please note that the suggestions are not checked. They are autogenerated from pyenchant library. No adjustments made from our side.

**Comment by funderburkjim** [comment]
Based on your examples,  looks like a good filter.

Will need human intervention before final changes.   Maybe @sanskritisampada can help.

**Comment by drdhaval2785** [comment]
Will place the script when I have made it work across all dictionaries. Maybe this weekend.

**Comment by drdhaval2785** [comment]
I am putting the text files here for cursory look.
As the suggestion was making the work too slow, I have done away with suggestions. It does not seem to be a major impediment.

[acc_error.txt](https://github.com/sanskrit-lexicon/csl-corrections/files/4800424/acc_error.txt)
[ae_error.txt](https://github.com/sanskrit-lexicon/csl-corrections/files/4800425/ae_error.txt)
[ap90_error.txt](https://github.com/sanskrit-lexicon/csl-corrections/files/4800426/ap90_error.txt)
[ben_error.txt](https://github.com/sanskrit-lexicon/csl-corrections/files/4800427/ben_error.txt)
[bhs_error.txt](https://github.com/sanskrit-lexicon/csl-corrections/files/4800428/bhs_error.txt)
[bor_error.txt](https://github.com/sanskrit-lexicon/csl-corrections/files/4800429/bor_error.txt)
[cae_error.txt](https://github.com/sanskrit-lexicon/csl-corrections/files/4800430/cae_error.txt)
[gst_error.txt](https://github.com/sanskrit-lexicon/csl-corrections/files/4800431/gst_error.txt)
[ieg_error.txt](https://github.com/sanskrit-lexicon/csl-corrections/files/4800432/ieg_error.txt)
[inm_error.txt](https://github.com/sanskrit-lexicon/csl-corrections/files/4800433/inm_error.txt)
[mci_error.txt](https://github.com/sanskrit-lexicon/csl-corrections/files/4800434/mci_error.txt)
[md_error.txt](https://github.com/sanskrit-lexicon/csl-corrections/files/4800435/md_error.txt)
[mw72_error.txt](https://github.com/sanskrit-lexicon/csl-corrections/files/4800436/mw72_error.txt)
[mwe_error.txt](https://github.com/sanskrit-lexicon/csl-corrections/files/4800437/mwe_error.txt)
[mw_error.txt](https://github.com/sanskrit-lexicon/csl-corrections/files/4800438/mw_error.txt)
[pe_error.txt](https://github.com/sanskrit-lexicon/csl-corrections/files/4800439/pe_error.txt)
[pgn_error.txt](https://github.com/sanskrit-lexicon/csl-corrections/files/4800440/pgn_error.txt)
[pui_error.txt](https://github.com/sanskrit-lexicon/csl-corrections/files/4800441/pui_error.txt)
[shs_error.txt](https://github.com/sanskrit-lexicon/csl-corrections/files/4800442/shs_error.txt)
[snp_error.txt](https://github.com/sanskrit-lexicon/csl-corrections/files/4800443/snp_error.txt)
[vei_error.txt](https://github.com/sanskrit-lexicon/csl-corrections/files/4800444/vei_error.txt)
[wil_error.txt](https://github.com/sanskrit-lexicon/csl-corrections/files/4800445/wil_error.txt)
[yat_error.txt](https://github.com/sanskrit-lexicon/csl-corrections/files/4800446/yat_error.txt)

**Comment by gasyoun** [comment]
> Will place the script when I have made it work across all dictionarie

Egaerly waiting.

```
224:agra:excelPage
229:agre:beforein
260:aMkuSaH:higgle
```

Opened `ap90_error` and can't get the idea what is to be corrected.

**Comment by sanskritisampada** [comment]
Sure !

**Comment by gasyoun** [comment]
@sanskritisampada so good to see you back.

**Comment by sanskritisampada** [comment]
Hey hi there!
I've been working with Jim on the Lanman corrections past few months.

Hope everyone is doing well amidst the Corona crisis.

Regards.

**Comment by gasyoun** [comment]
> working with Jim on the Lanman corrections past few months

Oh, nobody was aware of that other than Jim :)

**Comment by gasyoun** [comment]
> I am putting the text files here for cursory look.

@sanskritisampada and @AnnaRybakovaT are doing great work based on your scripting in summer, thanks. So not in vain!

**Comment by drdhaval2785** [comment]
I have missed a lot of fun in the recent past. 
How many dictionaries remain to be done @funderburkjim ?

**Comment by gasyoun** [comment]
>I have missed a lot of fun in the recent past.

Oh sure you have. Sampada and Jim are systematic on them, although lately it's become a bit slower.

**Comment by sanskritisampada** [comment]
Hi Dhaval...
We have only Yates to go...

**Comment by funderburkjim** [comment]
I also think that only Yates is to go,  but we'll do a confirmation of all the output files to be sure.

**Comment by drdhaval2785** [comment]
With #73 done, I think we have completed this exercise.
Time to close once @funderburkjim undertakes confirmation of all output files for making sure that we have not missed anything.

**Comment by sanskritisampada** [comment]
Checked the files.
Working to complete Benfey which was pending. Also a few cases in other
dictionaries seem to have been left out. Coordinating with Jim on those.
List will soon be complete!

Sampada

**Comment by funderburkjim** [comment]
I think we're done.
