### ISSUE TITLE
MD English Errors

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-corrections#15]
This comment devoted to correction of the English Errors in Macdonell Sanskrit-English Dictionary.

In #14,  a list of potential spelling errors for MD is in file [md_error.txt](https://github.com/sanskrit-lexicon/csl-corrections/files/4800435/md_error.txt).

There are various workflows that could be used for these corrections.  The following workflow 
seems to be quite straightforward, and relatively efficient.

**Comment by funderburkjim** [comment]
## proposed workflow: initial preparation

1. Download the md_error file with the above link
    * There are about 650 potential spelling errors, one per line
    * A sample line is `186:akzayya:neverfail`
    * Each line has 3 parts, separated by ':'
       * first part is the Cologne ID of the entry in md.txt (The 'L' number).  Example: *186*
       * second part is the headword of the entry in md.txt (The 'k1' or 'key1'). Example *akzayya* (in SLP1)
       * third part is the potentially misspelled word
         * In about 50 cases, there are two or more potential errors -  separated by comma.
2. Download a copy of the  digitization md.txt
   * md.txt is in csl-orig repository, at [md.txt](https://github.com/sanskrit-lexicon/csl-orig/blob/master/v02/md/md.txt).  Click on this link.  Then, click the 'download' button therein

**Comment by funderburkjim** [comment]
## session preparation
* Open local copy of md_error.txt in favorite text editor. Be sure you are opening with utf-8 encoding.
* Open local copy of md.txt similarly.
* Open your browser and input sample url for the scanned images:
   * https://www.sanskrit-lexicon.uni-koeln.de/scans/csl-apidev/servepdf.php?dict=MD&page=001

**Comment by funderburkjim** [comment]
## workflow for first potential error
This is line `181:akzamAlA:Arundhati` in md_error.txt
* In md.txt, find `<L>181` :  This will be the entry for akzamAlA Here it is:
   ```
   <L>181<pc>002-2<k1>akzamAlA<k2>akzamAlA
   {#akzamAlA#}¦akṣa-mālā, {%f.%} rosary; {%N. of%} Arundhati. <lbinfo n="4[]"/>
   <LEND>
  ```
* From `<pc>002-2`, we see that the scanned image is in 2nd column of page 2.
   * In your browser, edit the url to `page=002-2`, then load the image and find `akzamAlA` in scan.
      ![image](https://user-images.githubusercontent.com/6393033/86502070-1afb8e80-bd6d-11ea-9869-cba1c3f73cc5.png)
   * Examine `Arundhati` in scan.
   *  In this case, the spelling is correct.  No change to md.txt is required.
   *  Add a 4th field (OK) to this line of your local copy of md_error.txt, 
       `181:akzamAlA:Arundhati:OK`
       * Save md_error.txt

This completes the first example.

**Comment by funderburkjim** [comment]
## Workflow for second potential error
The second line in md_error.txt is `186:akzayya:neverfail`

* In md.txt, find `L>186`. Here is the entry for `akzayya`
   ```
   <L>186<pc>002-2<k1>akzayya<k2>akzayya<h>2
   {#akzayya#}¦a-kṣayya, {%n.%} {%water accompanied by %}
   <>{%a wish%} that {%it%} may neverfail; {@-udaka,@} {%n. id.%}.
   <LEND>
   ```
* If necessary, change the scanned image browser url to '...page=002', Then find 'akzayya' in column 2.
   ![image](https://user-images.githubusercontent.com/6393033/86502163-1aafc300-bd6e-11ea-8968-ad976a4ca7c6.png)
* We see that 'neverfail' in md.txt is missing a space.  We need to correct
*  In your editor window for md.txt,  make the change by adding a space between 'never' and 'fail'.
   * Then, Save md.txt
*  In your editor window for md_error.txt, add a fourth field `never fail`: 
    `186:akzayya:neverfail:never-fail`.  
   * Then save md_error.txt
* This completes the second example.

**Comment by funderburkjim** [comment]
## communicate results: md.txt

Following the above steps, you will be correcting only your local copy of md.txt.  
An additional step is needed to communicate the corrected md.txt, so that it may be revised in csl-orig
repository.

The simplest way to do this might be:
* zip md.txt  
* Send the zipped file as an attachment to Jim.
   Then, I'll do what is needed to install the corrections.

Suggestion:
* Do the first 10 corrections.  Then send zipped md.txt.   That way I can see that everything is ok as
   the project starts. Also, just for this first batch, send a zipped md_error.txt, again for initial review.
* Thereafter, just send me new zipped copies of md.txt after some reasonable number of cases.
   For example, say after every 60 cases.  That would be about 10 times.

@sanskritisampada    The above suggested workflow was designed with you in mind.
How does it sound? Workable?

**Comment by funderburkjim** [comment]
## note on editing md_error.txt
  It is ok to put comments in md_error.txt.  Just add comments as lines starting with a semicolon.  
  The local copy of md_error.txt is only for documenting the corrections.  It 
  

## note on editing md.txt
  Comments should NOT be made in md.txt.  md.txt is the *official* digitization for Macdonell dictionary.
  Only needed corrections should be made.

**Comment by gasyoun** [comment]
> The above suggested workflow was designed with you in mind.

Crystal clear algo, as usual.

**Comment by sanskritisampada** [comment]
Perfect, as usual.

**Comment by sanskritisampada** [comment]
Started the work.

**Comment by gasyoun** [comment]
> Started the work.

Thanks. Would love to see how you look as well, at least once.

**Comment by funderburkjim** [comment]
> Would love to see how you look as well

@gasyoun Here is a photo of @sanskritisampada  circa July 2020.

![IMG_4411](https://github.com/sanskrit-lexicon/csl-corrections/assets/6393033/86ae4780-6a1e-4599-bfbf-f1a4e994f132)
