### ISSUE TITLE
PW and other corrections

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-corrections#18]
S.J. at University Marburg submitted a batch of corrections via email.  

```
attached to this email is a list of some collected errors as well as the appropriate 
corrections to the online sanskrit dictionaries (mainly pw). These I have noted down 
during the last couple of years and I did not check if they have been corrected by now.

I hope, the dictionaries are being still maintained and the corrections may help 
improving it a little bit.
```
[Korrigenda_Cologne_Sanskrit_Lexicons.docx](https://github.com/sanskrit-lexicon/csl-corrections/files/5528059/Korrigenda_Cologne_Sanskrit_Lexicons.docx)

**Comment by funderburkjim** [comment]
Here is a reformatting of the 'docx' document:

## ﻿Cologne Sanskrit Lexicons – Korrigenda
|Worterbuch | L-Code | Lemma | Fehler | Korrektur | status|
|------ | ------ | ------ | ------ | ------ | ------|
|pw | 79433 | bhāma | 2) f. hāmā | 2) f. bhāmā | todo|
|pw | 83398 | manya | 1) Adv. | 1) Adj. | todo|
|pw | 119772 | sam | … mit einem … | … mit einem Nomen ... | todo|
|pw | 18424 | utpāda | Das hervorkommen | Das Hervorkommen | todo|
|pw | 56115 | na | (in imperat. Bed. | (in imperat. Bed.) | todo|
|pw | 25083 | kartay | (śauthilye) | (śaithilye) | todo|
|pw | 79579 | bhāvakartṛka | abstratum | abstractum | todo|
|pw | 63144 | para (5. Adv.) | d) … nur nur noch, ... | d) … nur, nur noch, ... | todo|
|pw | 39790 | ci 2. | ciketi, cinoti, citute | ciketi, cinoti, cinute | todo|
|pw | 52045 | dṛś | (Nom. दक्, *ved. दृङ्) | (Nom. दृक्, *ved. दृङ्) | todo|
|pw | 45621 | tāvant | 2)a) in Correlation mit वावत् | 2)a) in Correlation mit यावत् | todo|
|pw | 49096 | darbh | 1, दृफति | 1, दृभति | todo|
|pw | 50420 | diś | 21) 21) 21) 21) | 1) 2) 3) etc. | todo|
|pw | 50420 | diś | Mit आति | Mit अति | todo|
|pw | 50420 | diś | Mit आधि | Mit अधि | todo|
|pw | 50420 | diś | Mit आनु | Mit अनु | todo|
|pw | 50420 | diś | Mit आप | Mit अप | todo|
|pw | 50420 | diś | Mit आभि | Mit अभि | todo|
|pw | 50420 | diś | Mit आव | Mit अव | todo|
|pw | 96499 | leśa | … geringsten Spur von | … geringsten Spur von) | todo|
|pw | 101829 | viklitti | विक्लिति | विक्लित्ति | todo|
|pw | 63544 | parāmarśa | das packen an. | das Packen an. | todo|
|pw | 83428 | mamatā | ममताशृन्य | ममताशून्य | todo|
|pw | 90152 | yad | 2a) dass. Nach , denken | 2a) dass. Nach sagen, denken | todo|
|pw | 66234 | pāraṃparya | 1) … (DIE ältere | 1) … (die ältere | todo|
|pw | 19373 | upa | 1) -γ *nuter | 1) -γ *unter | todo|
|pw | 88171 | mṛgalekhā | Der Gazelle ... | Der als Gazelle ... | todo|
|pw | 21757 | ekatā | एकतामपिया | एकतामपि - या | todo|
|pw | 104641 | viśeṣa | सृगाल° ein besonders Schakal | सृगाल° ein besonderer Schakal | todo|
|pw | 4659 | anubodha | m. Widererregung | m. Wiedererregung | todo|
|pw | 96499 | leśa | geringsten Spur von | geringsten Spur von) | todo|
|pw | 9776 | arpaṇa | c) das Hineinsteckte | c) das Hineinstecken | todo|
|pw | 124662 | sāvadhāna | Mit einem , Infin. | Mit einem Infin. | todo|
|pw | 15591 | ārgala | m. f. = आर्गल. | m. f. = अर्गल. | todo|
|pw | 10397 | avadhāraṇa | b) genaues Bestimmen , | b) genaues Bestimmen, | todo|
|pw | 10397 | avadhāraṇa | Anders. | Andern. | todo|
|pw | 39790 | ci 2) | 2 , चिकेति , चिनोति , चितुते. | 2 , चिकेति, चिनोति, चिनुते . | todo|
|pw | 32737 | kṣudrakalpa | ritual | Ritual | todo|
|pw | 87878 | mūrch | mūrcchati | mūrchati | todo|
|pw | 87878 | mūrch | mūrcchita | mūrchita | todo|
|pw | 87878 | mūrch | mūrcchayati | mūrchayati | todo|
|pw | 87878 | mūrch | (abhi-) mūrchata | mūrchita | todo|
|pw | 87878 | mūrch | (vi-, saṃ-) mūrcchita | mūrchita | todo|
|pw | 87878 | mūrch | saṃmūrcchitavant | saṃmurcchitavant | todo|
|pw | 87878 | mūrch | āmūrcchayat formte | amūrchayat formte | todo|
|pw | 87878 | mūrch | gestaltes | gestaltete | todo|
|MW, 1899 | 19122 | a-vihita | for bidden | forbidden | todo|
|MW, 1899 | no hit | a-visvaram | xxx | xxx | todo|
|pw | 82767 | man | 2) … चिर्ंउ तब्मेने … | 2) … चिरं तन्मेने | todo|
|pw | 121154 | saṃbhāvana | 2) f) … saṃbhāvanojktita ... | 2) f) … saṃbhāvanojjhita | todo|
|pw | 59186 | nirūpita | … ūpay mit ni | … rūpay mit ni | todo|
|pw | 17461 | īdṛkṣa | īdagvidha, īdáś (Nom. īdáṅ und īdak), īdáśa (f. ī) und īdaśaka Adj. von diesem Aussehen, derartig, so beschaffen, ein solcher. (yádi) īdágā́ṃra | īdṛgvidha, īdṛś (Nom. īdṛṅ und īdṛk), īdṛśa (f. ī) und īdṛśaka Adj. von diesem Aussehen, derartig, so beschaffen, ein solcher. (yádi) īdṛgā́ṃra Achtung: Akzentzeichen! | todo|
|pw | 70210 | prakaṭa | prakaṭm und prakaṭa° | prakaṭam und prakaṭa° | todo|
|pw | 44264 | tathā | 6) … tthā cotkam | 6) … tathā coktam | todo|
|pw | ? | *vāstra | keine Trefferanzeige | Adj. mit Zeug überzogen | todo|
|pw | 4848 | anuveśa | hereintreten | Hereintreten | todo|
|pw | 130221 | sauhṛda | 1) Adj. von Freunde | 1) Adj. vom Freunde | todo|
|pw | 130221 | sauhṛda | 3b) das Freundesein | 3b) das Freundsein | todo|
|pw | 39963 | citra | 4) n. g) *buntheit | 4) n. g) * Buntheit | todo|
|pw | 95422 | lagna | 1)  Adj.  » s. u. लग् une 1. लज्. | 1)  Adj.   s. u. लग् und 1. लज्. | todo|
|pw | 74652 | prāsaṅgika | Adj. (F. ī; ā fehlerhaft) | Adj. (f. ī; ā fehlerhaft) | todo|
|pw | 49096 | darbh | mit sam; 1) zu eine , Büschel gebunden | mit sam; 1) zu einem Büschel gebunden | todo|
|pw | 33914 | khelana | 1a) … (der augen) | 1a) … (der Augen) | todo|
|MW, 1899 | 247985-247992  (247984 missing!) | subhaga | m. | f. | todo|
|pw | 46649 | tūṣṇībhāva | m. wohl fehlerhaft für tūṣṇībhāva | m. wohl fehlerhaft für tūṣṇīṃbhāva | todo|
|pw | 87422 | muc (+ vi) | 5) eine Ort verlassen | 5) einen Ort verlassen | todo|
|pw | 116967 | saṃsṛti | f. = saṃsārra | f. = saṃsāra | todo|
|pw | 73174 | pravāha | β … Fehlerhaft ... | β … fehlerhaft ... | todo|
|pw | 89044 | mocaka | a) befreiend erlösend von ... | a) befreiend, erlösend von ... | todo|
|pw | 79595 | bhāvana | 2 a) das bewirken, zur Erscheinung bringen | 2 a) das Bewirken, zur Erscheinung Bringen | todo|
|pw | 30679 | keli | m.f. auch °lī) | m.f. (auch °lī) | todo|
|pw | 2249 | atyanta | 2) atyantagn und (Fehler nur im NWS!) | 2) atyantam und | todo|
|pw | 49037 | 1. dar | Mit a | Mit ā | todo|
|pw | 49037 | 1. dar | - 1) sich spalten ... | - 1) sich spalten ... | todo|
|pw | 7166 | abdhi | 1) Meer | m. 1) Meer | todo|
|pw | 121831 | sarvathā | 1) in allen, Fällen | 1) in allen Fällen | todo|
|pw | 13830 | ācchādana | 1) … verhüllen, ... | 1) … Verhüllen, ... | todo|
|pw | 12912 | asthiti | f. schlechter … | f. schlechte ... | todo|
|pw | 28439 | kuṇḍa | 6) n. a) … eines Kreise | 6) n. a) … einem Kreise | todo|
|pw | 83878 | malīmasa | 1) a) … (ein. und übertr.) | 1) a) … (eig. und übertr.) | todo|
|pw | 36163 | gṛdhnu | Ad. | Adj. | todo|
|pw | 40240 | cira | 5) carāya | 5) cirāya | todo|
|pw | 80202 | saṃbhū | 14) b) *fassen, Raum haben für.Caus. | 14) b) *fassen, Raum haben für. – Caus. | todo|
|pw | 80202 | saṃbhū Caus. | 11) annehmen, dass es Etwas set | 11) annehmen, dass es Etwas sei | todo|
|pw | 70407 | prakhya | 2) b) Ganz | 2) b) Glanz | todo|
|Schmidt | ? | apratisaṃkrama | … woraud sich … | … worauf sich ... | todo|
|pw | 123860 | sānāthya | n. Bestand, ... | n. Beistand, ... | todo|
|pw | 7166 | abdhi | 1) Meer | m. 1) Meer | todo|
|pw | 121831 | sarvathā | 1) in allen, Fällen | 1) in allen Fällen | todo|
|pw | 13830 | ācchādana | 1) … verhüllen, ... | 1) … Verhüllen, ... | todo|
|pw | 12912 | asthiti | f. schlechter … | f. schlechte ... | todo|
|pw | 28439 | kuṇḍa | 6) n. a) … eines Kreise | 6) n. a) … einem Kreise | todo|
|pw | 83878 | malīmasa | 1) a) … (ein. und übertr.) | 1) a) … (eig. und übertr.) | todo|
|pw | 36163 | gṛdhnu | Ad. | Adj. | todo|
|pw | 40240 | cira | 5) carāya | 5) cirāya | todo|
|pw | 80202 | saṃbhū | 14) b) *fassen, Raum haben für.Caus. | 14) b) *fassen, Raum haben für. – Caus. | todo|
|pw | 80202 | saṃbhū Caus. | 11) annehmen, dass es Etwas set | 11) annehmen, dass es Etwas sei | todo|
|pw | 70407 | prakhya | 2) b) Ganz | 2) b) Glanz | todo|
|Schmidt | ? | apratisaṃkrama | … woraud sich … | … worauf sich ... | todo|
|pw | 123860 | sānāthya | n. Bestand, ... | n. Beistand, ... | todo|
|pw | 114581 | śaurya | 2) … Vgl. śaurya | 2) … Vgl. saurya | todo|
|pw | 83493 | mayūravyaṃsaka | = ghūrtamayūra | = dhūrtamayūra | todo|
|pw | 18132 | uttara | 4 d) uḥkhottara | 4 d) duḥkhottara | todo|
|pw | 87391 | mukhya | 1) … Rücksichten steht mukhaya ... | 1) … Rücksichten steht mukhya ... | todo|
|pw | 23823 | katham | 3) … katham ḷh iyaṃ … | 3) … katham | iyaṃ ... | todo|
|pw | 23823 | katham | 9 b) … kthaṃ kathaṃ cid ... | 9 b) … kathaṃ kathaṃ cid ... | todo|
|pw | 96430 | ḷṛṭ | ḷṭ | ḷṛṭ | todo|
|pw | 87041 Fehler nur im NWS! | miṣ | miṣ, bhiṣati | miṣ, miṣati | todo|
|pw | 122814 | saha | 2) … Hier und da abgeschwächt fehlerhaft Instr. wie das deutsche mit | 2) … Hier und da abgeschwächt für den einfachen Instr. wie das deutsche mit | todo|
|pw | 122814 | saha | 3) b) mit dem Beleitend | 3)b) mit dem Begleitenden | todo|
|pw | 27616 | kāṣṭhakuṭṭa | Ficus bengalensis. | Picus bengalensis. | todo|

**Comment by funderburkjim** [comment]
I'll work through these in the coming days.

**Comment by gasyoun** [comment]
Such a list - most of it must be still valid.

**Comment by funderburkjim** [comment]
Corrections now made.

Please review the 'status' column of the above table.

Notes:
* There are some duplicates.   I think these were present in the original docx file
* There are a small number with questions.  Search for '?' in above table.
