### ISSUE TITLE
Preliminary instructions for Correction installation

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-corrections#2]
The following comment shows the steps done in installing pending user submitted corrections for
'ae' dictionary.  There are lots of 'motivational' comments -- ie., comments about 'why' various steps are done

Interested participants should provide revisions.  After a period of revision, we can put this into
a 'doc' directory.

There should probably also be a short version,  mentioning all the steps, but skipping the wordy
explanations.

**Comment by funderburkjim** [comment]
# Correction installation: local steps

It is assumed that the user has a local installation, and that
all repositories are in a 'cologne' directory.
The script steps further assume that the user has an open terminal,
and that the 'cologne' directory is the current directory
## Step 1. pull repositories
```
# get the latest version of the digitizations
cd csl-orig
git pull
cd ../  # back to cologne
# get the latest version of the corrections
cd csl-corrections
git pull
cd ../ # back to cologne
```

## look for bad records in cfr.tsv
When users submit corrections, the correction_form program posts the
results to file csl-corrections/app/correction_response/cfr.tsv.

>
 cfr.tsv : **c**orrection **f**orm **r**esponse  **t**ab **s**separated **v**alues.
 The 'tsv' file type is one used in Google Docs.


Each line in cfr.tsv represents a user-submitted correction.
Sometimes there are garbage values, which need to be deleted, or altered.
So I usually open cfr.tsv in a text editor (cfr.tsv is assumed utf-8 encoded)
and go to the bottom of the (large) file. Then I go back up until I find
the last record whose 'status field' (the last of the tab-delimited fields)
does not show that it has been corrected.  This status field will either 
* contain a colon -- typically `Caujolle:Corrected 07/17/2019`  
* contain no colon, but the user name or email-address: `Caujolle`
* be empty.

The last two cases are ones that have NOT been processed.  When a correction
has been processed, the `:Corrected 07/17/2019` is added to the line in
cfr.tsv; and the presence of the ':' character is used by the cfr_adj.py 
program to distinguish between cases that have been done and 'pending' cases,
which have yet to be done.

So, I find where the pending cases start in cfr.tsv, then page down
looking for 'odd' lines.  Sometimes, people will not understand how to
use the correction form, and will not provide enough information to warrant
further action.  I usually delete these records in the text editor.
Other times, unfriendly people put obviously wrong data in the response,
in an attempt to cause a security breach on the Cologne server.  I also 
delete such lines from cfr.tsv.

After deleting any of the pending lines at the bottom of cfr.tsv, use the
text editor to save the file.

## correctionform.txt 
``` 
cd csl-corrections
sh redo_cfr.sh
```

This program reads through cfr.tsv.
Here is the terminal output from the latest run:
```
$ sh redo_cfr.sh
regenerate correctionform.txt and dictionaries/xxx/xxx_correctionform.txt
rewriting correctionform.txt ( 101 pending )
24542 lines read from app/correction_response/cfr.tsv
101 cases are pending
rewriting dictionaries/ae/ae_correctionform.txt ( 3 pending )
rewriting dictionaries/skd/skd_correctionform.txt ( 4 pending )
rewriting dictionaries/vcp/vcp_correctionform.txt ( 1 pending )
rewriting dictionaries/pwg/pwg_correctionform.txt ( 5 pending )
rewriting dictionaries/mw/mw_correctionform.txt ( 29 pending )
rewriting dictionaries/wil/wil_correctionform.txt ( 6 pending )
rewriting dictionaries/bur/bur_correctionform.txt ( 11 pending )
rewriting dictionaries/stc/stc_correctionform.txt ( 4 pending )
rewriting dictionaries/pw/pw_correctionform.txt ( 11 pending )
rewriting dictionaries/ccs/ccs_correctionform.txt ( 2 pending )
rewriting dictionaries/ap90/ap90_correctionform.txt ( 14 pending )
rewriting dictionaries/yat/yat_correctionform.txt ( 1 pending )
redo_cfr.sh is finished
```

The main correctionform.txt file shows each record in cfr.tsv in a
more readable form.  The records are printed in reverse-order from cfr.tsv.
The first few lines are:
```
Sanskrit Lexicon Correction Form History
As of December 17, 2019
24541 correction records, with 101 PENDING

Case 24541: 12/17/2019 dict=MW, L= , hw=maatR^ikaa, user=
old = 
new = 
status = PENDING
------------------------------------------------------------------------

Case 24540: 12/17/2019 dict=MW, L= 260415, hw=हथ, user=sanaatani
old = हठ
new = In Printed book page 1287,3 it is scripted Haṭha. Notice the diacritic mark of the letter ṭ.
comment = Typo. Not infrequently I have encountered words that are present in MW but not in Apte. So I go about seeking clarification from my knowledgeable friends. That is how I learnt about हथ
status = PENDING
------------------------------------------------------------------------
```

As you see from the redo_cfr.sh output, output is also generated for each
dictionary.  We see that there are 3 pending corrections for dictionary 'ae';
Here is the top of dictionaries/ae/ae_correctionform.txt:
```
Sanskrit Lexicon Correction Form History for AE
As of December 17, 2019
94 correction records, with 3 PENDING

Case 24469: 09/06/2019 dict=AE, L= 11278, hw=Woman, user=sanaatani
old = कुलांगमा
new = कुलांगना. It is better to use the अनुनासिक of the कवर्ग - कुलाङ्गना। The svarAnunAsika (ं) is for अवर्गीयव्यञ्जनाः - संयम, संरम्भ, संलग्न, संवरण, संशय, संस्कार, संहार
comment = Typo.
status = PENDING
------------------------------------------------------------------------

etc.
```

## correcting one dictionary.

It is best to focus on the pending corrections for just one dictionary.
I'll start with 'ae' dictionary, which shows 3 pending corrections.

We need to open 3 text files in a local text editor; be sure all are opened
with utf-8 encoding.
* csl-corrections/app/correction_response/cfr.tsv  -- we'll mark the
  pending 'ae' corrections as ':Corrected 12/17/2019' 
* csl-corrections/dictionaries/ae/ae_correctionform.txt  It's easier
  to read the correction submissions here than in cfr.tsv
* csl-orig/v02/ae/ae.txt   This is the digitization of 'ae'. We'll be 
  correcting it.  

## first correction
Here is the entry from ae_correctionform.txt:
```
Case 24469: 09/06/2019 dict=AE, L= 11278, hw=Woman, user=sanaatani
old = कुलांगमा
new = कुलांगना. It is better to use the अनुनासिक of the कवर्ग - कुलाङ्गना। The 
svarAnunAsika (ं) is for अवर्गीयव्यञ्जनाः - संयम, संरम्भ, संलग्न, संवरण, संशय, संस्कार, संहार
```

We can find the entry in ae.txt by searching for 'L>11278'.
```
<L>11278<pc>497<k1>woman<k2>woman
{@Woman,@}¦ {%s.%} {#strI, nArI, aMganA, abalA, yo-#}
<div n="lb"/>{#-zit, vanitA, lalanA, yozA, sImaMtinI, vaDUH,#}
<div n="lb"/>{#vAmA, mahilA;#} ‘nobly-born w.’ {#kulAM-#}
<div n="lb"/>{#-gamA, kulajA,#} ‘young w.’ {#yuvatiH-#}
```
We also should look at the scanned image.  Open a browser and 
look up 'woman' in 'ae' dictionary; then get the scanned image.
It is fairly clear from the image that '-gamA' should be '-ganA'.
I also looked up, in MW, 'kulANganA' (slp1 spelling) and found his
gloss as 'a respectable or virtuous woman'.  So think digitization
should be changed to '-ganA'.

Make this change in ae.txt, using text editor; save ae.txt file.

Now find this submission in cfr.tsv, and append ':Corrected 12/17/2019';
save cfr.tsv.

Since this user gave an email, you might jot down the email in a sticky note
for later sending an acknowledgment.

## second correction to ae
From ae_correctionform.txt, the next two pending corrections are:
```
------------------------------------------------------------------------

Case 24448: 07/26/2019 dict=AE, L= 382, hw=Anhelation, user=sanaatani
old = 
new = 
comment = None. A little while ago I wrongly suggested that it could be INHALATION. Pls ignore my suggestion. Anhelation is correct. Sorry for the inconvenience.
status = PENDING
------------------------------------------------------------------------

Case 24447: 07/26/2019 dict=AE, L= 382, hw=Anhelation, user=sanaatani
old = Is it inhalation?
new = 
status = PENDING
```

Here we see that the two submissions are related, and that actually is no change needed to ae.txt.

So let's just add ':Corrected 12/17/2019' to the status field of cfr.tsv for
these two, then save cfr.tsv.

## Install the correction in local ae display

This step is optional, but a good idea.  In our local installation of
the ae displays  (e.g., basic display cologne/ae/web/webtc/indexcaller.php),
the displayed data will still show '-gamA'.  The reason is that the
displayed data comes from ae/web/sqlite/ae.sqlite, which in turn comes from
ae/pywork/ae.xml.   To get the change in csl-orig/v02/ae/ae.txt reflected
in ae/web/sqlite/ae.sqlite, we need to run a script.

```
# first relocate
cd csl-pywork/v02
# find the script for updating just 'ae' in our local installation.
# It is one of the lines in redo_xampp_all.sh
# Use grep:
grep ae redo_xampp_all.sh
# This gives two lines
#   sh generate_dict.sh ae  ../../ae
#   sh generate_dict.sh cae  ../../cae
# We want the first line, so copy and paste it in the terminal to run:
sh generate_dict.sh ae  ../../ae
```

The output is kind of long -- but most of it can be skipped over.
Basically, you're looking for some 'error' condition which theoretically
could occur.
```
$ sh generate_dict.sh ae  ../../ae
updating for websanlexicon for dictionary ae to /c/xampp/htdocs/cologne/ae
regenerate ae headwords
BEGIN redo_hw.sh
construct xxxhw.txt
0 extra headwords from hwextra/ae_hwextra.txt
89606 lines read from ../orig/ae.txt
11360 entries found
11360 lines written to aehw.txt
construct xxxhw2.txt
construct xxxhw0.txt
DONE redo_hw.sh
regenerate ae.xml and postxml files
BEGIN redo_xml.sh
construct ae.xml...   <<< after this, ae.xml is constructed
xmllint on ae.xml...
redo_xml.sh: line 5: xmllint: command not found   
    <<< is an error, since 'xmllint' is not available on windows xampp.
    <<< but just ignore it
ae.sqlite...
remaking input.txt...
11365 lines from ../ae.xml
remaking sqlite table...
Error: near line 1: no such table: ae   <<< This also is non-critical error
0       key     VARCHAR(100)    1               0
1       lnum    DECIMAL(10,2)   0               0
2       data    TEXT    1               0
11360
moving ae.sqlite to web/sqlite/   <<< Now, we've got ae.sqlite
11360 records read from ../ae.xml
11345 records written to query_dump.txt
END redo_xml.sh
regenerate downloads
BEGIN: downloads/redo_txt.sh
remove old aetxt.zip
copying files from ../pywork to txt/
create new aetxt.zip
BEGIN: downloads/redo_xml.sh
remove old aexml.zip
copying files from ../pywork to xml/
create new aexml.zip
BEGIN: downloads/redo_web1.sh
remove old aeweb1.zip
```

If you want to further check, you can look up 'woman' in your local
installation.  E.g. use url `http://localhost/cologne/ae/web/webtc/indexcaller.php?key=woman`.   I just did this and now see '-ganA', so the change is
installed locally.


## push dictionary changes to Github

We need to sync our local installations of csl-corrections and csl-orig
to github.
```
cd csl-corrections
git add .
git commit -m "User corrections for AE"
git push
# and now for csl-orig
cd ../csl-orig
git add .
git commit -m "1 User correction for AE."
git push
```

Dhaval may prefer further detail regarding the commit message ?

## push dictionary changes to Cologne server.
This must be done by Dhaval or Jim.  

What needs to be done on Cologne server:
* 'git pull' for csl-corrections 
* 'git pull' for csl-orig.
* In csl-pywork/v02, update 'ae':
  `sh generate_dict.sh ae  ../../AEScan/2020/
  * Good to check for errors, especially at 'xmllint'.
* Jim should email Dhaval, or vice-versa, so both know about the update

**Comment by drdhaval2785** [comment]
One suggestion regarding commit messages. We can keep it sfandardized and informative

Suggested format
`dict:lnum1,lnum2,....`

```
cd csl-corrections
git add .
git commit -m "ae:11278"
git push
# and now for csl-orig
cd ../csl-orig
git add .
git commit -m "ae:11278"
git push
```

**Comment by drdhaval2785** [comment]
@funderburkjim, 
Let me try to correct WIL dictionary according to your steps shown above.
If I get stuck somewhere, I will modify the abovementioned comments accordingly.

**Comment by funderburkjim** [comment]
> git commit -m "ae:11278"

This is fine with me. Have edited the instructions comment above accordingly.

**Comment by funderburkjim** [comment]
## suggested optional form(s) for commit message.
I also put the headword in a commit; can consider this an option  to lnum.
Also, mentioned that one correction was classified as a print change - also optional.
`pwg:35439,droRa; 19764,kram; 101905,SreyaMs (print change); 102723,sa; 102722,sa`

@drdhaval2785  -  any objection to these optional forms?

**Comment by funderburkjim** [comment]
## print change step

Occasionally, we'll make a 'print change'.   This occurred in today's change to SreyaMs in pwg.
The digitization was aufgefuhrte, and the suggested change is aufgeführte.  Scanned image
doesn't show the umlaut.  Using Google translate for `aufgefuhrte` resulted in 'Did you mean `aufgeführte`?'  While it is possible that aufgefuhrte was correct German at the time
PWG wrote (1855),  it seems reasonable to me to take the suggested `aufgeführte` spelling.
Since this is a 'print change'  (a change to what our scan shows),  it is obligatory to update
the `csl-corrections/dictionaries/pwg/pwg_printchange.txt` file.  Here is what was added to the bottom of the file:
```
----------------------------------------------------------------------
12/18/2019
Change submitted by user h.c.jahr; confirmed with Google translate by ejf
L code : Headword : Old  : New : Comment
102722 : SreyaMs : aufgefuhrte : aufgeführte : Missing umlaut.
```

This comment should be part of the **correction installation: local steps** mentioned above.

**Comment by drdhaval2785** [comment]
No problems with suggested commit message.
