### ISSUE TITLE
Greek in Lanman

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-corrections#22]
This issue separated out from a comment in [another issue](https://github.com/sanskrit-lexicon/csl-homepage/issues/4#issuecomment-732376462).

Lanman provides etymological comparisons to Greek in many of the Vocabulary entries.
(about 900 instances)

The current digitization [lan.txt](https://github.com/sanskrit-lexicon/csl-orig/blob/master/v02/lan/lan.txt)
marks the location of the Greek text, but does not provide the Greek text itself.

An enhancement would be to provide this Greek text, as has been done for MW and for
several other Cologne digitizations (see https://github.com/sanskrit-lexicon/GreekInSanskrit/issues).

**Comment by gasyoun** [comment]
So it's time for @jmigliori, right?

**Comment by jmigliori** [comment]
I have a lot of free time this winter if you’re looking for more Greek transcription

**Comment by gasyoun** [comment]
> looking for more Greek transcription

We sure are, right @funderburkjim ?

**Comment by funderburkjim** [comment]
@jmigliori   Hi!  Appreciate your generous offer.

Here's a suggested workflow:
## Step 1: download the pdf 
* go to https://github.com/funderburkjim/lanman/tree/master/pdfs
* right-click Save-link-as `sanskritreaderw00lanm_bw.pdf`

This is pdf of whole book.  The Vocabulary starts on page 111:
![image](https://user-images.githubusercontent.com/6393033/100799688-75b81580-33f3-11eb-815d-8215c58c338b.png)

## Step 2. Download digitization

* go to https://www.sanskrit-lexicon.uni-koeln.de/scans/LANScan/2020/web/webtc/download.html
* right-click Save-Link-As `lantxt.zip`
* Unzip.  The digitization file is `lan.txt`

**Comment by funderburkjim** [comment]
##  input Greek

* open the pdf in your favorite pdf reader.
  and go to the page 111,
* open lan.txt in a text editor.  
  * Be sure you are opening with 'utf8-encoding', which is the encoding used in this file
     for all the non-ascii text.
* The Greek text locations are identified by `<lang n="greek"></lang>`. For example,
   the first instance is on line 24 of lan.txt:
   ![image](https://user-images.githubusercontent.com/6393033/100800550-c1b78a00-33f4-11eb-9fb6-6bea616e4414.png)
* You will type in the Greek text where indicated  `<lang n="greek">XXX</lang>`
* Note the `<pc>111-a` indicates the page (111) and column (a or b) of the pdf.
* When you've entered the Greek text, use your editor to search for the next case by searching for the
   next ``<lang n="greek"></lang>`
* Find the corresponding spot in the pdf, and enter the Greek text
* etc.
* When you save your local copy, try to confirm it is being saved in utf-8 encoding.  Usually this is the case.

## How to communicate the results
* zip your local copy of lan.txt
* send the zipped lan.zip to me somehow, such as
  * by email attachment
  * upload to drop box or some other cloud location, and send me the link (or mention link in a comment here
    on Github).

## Trial run
Let's be sure that encoding and other issues are being handled properly.

Enter the first few Greek instances into lan.txt,  and communicate the lan.zip to me.

## Is this workflow ok?

This workflow is a bit more 'direct' than that we used in your previous work.
I'm suggesting it because it seems to be a bit easier on my end,  and perhaps also on your end.

What do you think?

**Comment by jmigliori** [comment]
My pleasure, @funderburkjim. I’ve just done the first page’s worth and the zip is here: https://classroom.google.com/u/1/c/MTY0MzU4Njc2OTEy/m/MjEwOTk1NTMzMjIz/details If that looks good, I’ll get to work on the rest.

**Comment by funderburkjim** [comment]
@jmigliori   I couldn't find the zip.  Here's what I see:

![image](https://user-images.githubusercontent.com/6393033/100807022-94bca480-33ff-11eb-81eb-79b9ad7a17bc.png)

**Comment by jmigliori** [comment]
I must have pasted the wrong link. This should work: https://drive.google.com/file/d/18NwUZholsTXXy1J1GcEOyjvx5a7_DD6J/view?usp=sharing

**Comment by funderburkjim** [comment]
Got the file.

No encoding problems,  but Greek not quite in the right spot.
Example:
```
OLD:
(part), {@√am,@} <ls n="wg,1197">1197a</ls>: <ab>cf.</ab> <lang n="greek"></lang>, <ab>Lat.</ab> {%um-erus,%}

YOUR correction:
(part), {@√am,@} <ls n="wg,1197">1197a</ls>: <ab>cf.</ab> <lang n="ὦμ-ος"></lang>, <ab>Lat.</ab> {%um-erus,%}

PREFERRED:
(part), {@√am,@} <ls n="wg,1197">1197a</ls>: <ab>cf.</ab> <lang n="greek">ὦμ-ος</lang>, <ab>Lat.</ab> {%um-erus,%}

```
So,  leave `<lang n="greek">` unchanged, put the Greek text between `>` and `</lang>`.

**Comment by jmigliori** [comment]
Ah! Understood.

**Comment by gasyoun** [comment]
> So, leave <lang n="greek"> unchanged, put the Greek text between > and </lang>.

Yap, with Jim even I understood ))

**Comment by jmigliori** [comment]
@funderburkjim Just a heads-up a number of the Greek tags in Lanman aren’t Greek, but Old English (“AS.” in the dictionary). Specifically, it tags the letters ð and þ as Greek. I have experience with Old English, so this hasn’t been an issue. I did catch, however, one instance where a þ was scanned as a p and not tagged. Here is the entry with the fixed þ (in the second-to-last line):

<L>1708<pc>162-a<k1>tan<k2>tan<h>1
{@√1tan@}¦ ({@tanóti, tanuté; tatā́na, tené@}
[<ls n="wg,794">794e</ls>]; {@átānīt; taṃsyáte; tatá; tántum;@}
{@tatvā́; -tátya; tāyáte@} [<ls n="wg,772">772]</ls>). <div n="2"/>{@—1.@}
stretch, {%<ab>trans.</ab> and <ab>intrans.</ab>;%} extend, reach;
spread over; <div n="2"/>{@—2.@} continue, endure, <ls n="lan,79,13">79<sup>13</sup></ls>;
<div n="2"/>{@—3.@} stretch (a weft {%or%} a line); continue
(the line of a family); <div n="2"/>{@—4.@} {%metaphorically,%}
of sacrifice and supplication (which are
compared with a weft), perform, make.
[<ab>cf.</ab> <lang n="greek">τάνυμαι</lang>, ‘stretch’; <ab>Lat.</ab> {%tenēre,%} ‘hold,’
{%tendere,%} ‘stretch’; <ab>AS.</ab> {%ϸenian,%} <ab>Ger.</ab> {%dehnen,%}
‘stretch’: see also {@tanu.@}]

**Comment by gasyoun** [comment]
> one instance where a þ was scanned as a p and not tagged.

Nice catch, thanks. I hope we will have different indexes for different language words after.

**Comment by funderburkjim** [comment]
Jonathan   for the cases where the `<lang n="greek"></lang>`  is not greek, 
how does lan.txt look after the correction.   Your example looks like you removed  `<lang n="greek"></lang>`,
which seems a good solution.   Right?

**Comment by funderburkjim** [comment]
@jmigliori   Discard my previous comment.

Note on Github comment:   I edited your example comment to put all those lines of text between a pair of
triple backticks.   Single backticks can also be used for short strings.  Now `<lang n="Greek"></lang>`  shows
in your example comment, whereas previously it was absent.   This is Github's way of allowing HTML or XML
tags to be either treated as text (using backticks)  or treated as HTML  (no backticks).

**Comment by funderburkjim** [comment]
> hope we will have different indexes

Such as `<ab>AS.</ab> <ab lang="AS">{%ϸenian,%}</lang>`   ?

**Comment by gasyoun** [comment]
> Such as <ab>AS.</ab> <ab lang="AS">{%ϸenian,%}</lang> ?

Right. I want to know all `<ab>AS.</ab>` words listed alphabetically from Lanman entries and to what Sanskrit entries they correspond. How many different languages/scripts are listed in <lang n="*"> around all dictionaries?

Tried to give a sample. I dream of all kinds of possible indexes for etymological research:
1) By language:
1.1) Gk.
1.1.1) one Greek word (`ὦμος`) = one row (contained in `aMsa` Sanskrit entry, L number added)
ὦμος			aMsa (92.1)
ἄσιλλα			aMsa (92.1)
κεράννυμι		kF (55567)
κίρνημι			kF (55567)

1.1.2) several Greek words kept together, one initinal Sanskrit word "nest" = one row 
ὦμος, ἄσιλλα		aMsa (92.1)
κεράννυμι, κίρνημι	kF (55567)

1.1) Sanskrit - Greek
aMsa (92.1)	ὦμος, ἄσιλλα
kF (55567)	κεράννυμι, κίρνημι

![alt](https://user-images.githubusercontent.com/80761/102699891-85d84d80-4259-11eb-9db3-af15a7b56961.JPG)

**Comment by funderburkjim** [comment]
> I want to know all <ab>AS.</ab> 

This kind of analysis is what Python is good for.  Possibly out of scope for @jmigliori 

Remind on this when @jmigliori has completed his work.

**Comment by jmigliori** [comment]
Definitely out of my scope!

**Comment by jmigliori** [comment]
@funderburkjim et al., here’s the finished Lanman Greek: https://drive.google.com/file/d/18NwUZholsTXXy1J1GcEOyjvx5a7_DD6J/view?usp=sharing

**Comment by funderburkjim** [comment]
@jmigliori   Pleasant surprise to see this!

In processing, I found only ONE problem that needs your attention:

## problem at 'gati'

At line 6512 of revised lan.txt:
```
<ls n="lan,65,10">65<sup>10</sup></ls>, <ls n="lan,66,6">66<sup>6</sup></ls>, <ls n="lan,66,21">66<sup>21</sup></ls> <ab>ff.</ab> [{@√gam,@} <ls n="wg,1157">1157</ls>: <ab>cf.</ab> <lang n="  /lang>,    <<<<<<
‘going, power to go.’]
```
Here is scan:
![image](https://user-images.githubusercontent.com/6393033/106819303-99901580-6647-11eb-8967-8992c61ea498.png)

Just put  the Greek in  a comment below.

**Comment by jmigliori** [comment]
@funderburkjim It was so much easier working from the txt file. Having everything in one place and be searchable really sped it along.

βά-σι-ς

**Comment by funderburkjim** [comment]
@jmigliori    Got the change.  All those lovely Greek words are now available in the displays of Lanman dictionary,
thanks to you.

For example, see entry for guru: https://sanskrit-lexicon.uni-koeln.de/simple/lan/guru

**Comment by funderburkjim** [comment]
@gasyoun  and @drdhaval2785 

Are there other  Cologne dictionaries which have Greek text not yet provided by @jmigliori ?

**Comment by gasyoun** [comment]
> Are there other Cologne dictionaries which have Greek text

Not that I'm aware of, still sure something is missing. I could check that one day.

**Comment by gasyoun** [comment]
@funderburkjim INM is without, but it is a programmatically solvable task, @YevgenJohn right?
![greeks](https://user-images.githubusercontent.com/80761/112236812-5ec35a80-8c52-11eb-948a-735c8d5ce18d.JPG)

**Comment by drdhaval2785** [comment]
Lanman is done anyways.
We close Lanman thing, and open INM Greek in another.
