### ISSUE TITLE
English word Corrections and Git

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-corrections#23]
@AnnaRybakovaT 

OK -  We'll consider it an experiment to get you started using Git, starting at zero.

**Comment by funderburkjim** [comment]
## Install git bash for windows
Go to https://gitforwindows.org/ and click Download button.

Then,
click the 'save' button
![image](https://user-images.githubusercontent.com/6393033/101940071-ec070580-3bb3-11eb-8d37-a41a70e7c614.png)

This downloads the installer  (named Git-2.29.2.3-64-bit.exe when I just did the download).
 When the download is finished, open the installer.

You will get a security dialog such as *Do you want to allow this app to make changes to your device?*.
Click 'Yes'.

Then You will get a license dialog: Click 'Next>'
![image](https://user-images.githubusercontent.com/6393033/101940781-01306400-3bb5-11eb-8a76-510b6757dbee.png)

Then you will see *Choosing the default editor used by Git* . Click Next.
   Don't worry what 'Vim' is.  You probably will never need to know about Vim.  
![image](https://user-images.githubusercontent.com/6393033/101941076-7865f800-3bb5-11eb-8abf-7b25950a1c7b.png)

Another choice: Click Next:
![image](https://user-images.githubusercontent.com/6393033/101941168-9af81100-3bb5-11eb-9a00-e2bdcfd059c5.png)

Still another incomprehensible choice:  Click Next
![image](https://user-images.githubusercontent.com/6393033/101941243-b531ef00-3bb5-11eb-8d7b-fa11a6a5ae6f.png)

And again, click Next:
![image](https://user-images.githubusercontent.com/6393033/101941320-d0046380-3bb5-11eb-9698-78f8fb7c4778.png)

And again, click Next:
![image](https://user-images.githubusercontent.com/6393033/101941405-ed393200-3bb5-11eb-8f21-ebe8ebd6ece8.png)
And again, click Next:
![image](https://user-images.githubusercontent.com/6393033/101941560-2a052900-3bb6-11eb-9335-fa50fa89657d.png)



    
And FINALLY click Install:

![image](https://user-images.githubusercontent.com/6393033/101942053-e4952b80-3bb6-11eb-8260-b683a97227f3.png)

You will now see 'Installing .. Please wait while Setup installs Git on your computer'.   May take a few minutes.
When this is done, you'll see the last window of the installer (Uncheck 'View Release Notes' if you want).
Then click Finish.
![image](https://user-images.githubusercontent.com/6393033/101942331-5bcabf80-3bb7-11eb-92a9-4501dadfda8c.png)

**Comment by funderburkjim** [comment]
I put in all the gory details above,  but it is really fairly simple:
You download an installer,  run the installer and accept all the default settings.
Once *Git for Windows* is installed,  you are ready to start learning how to use it.
Git is a 'version control system', certainly the most widely used currently.  You can
find lots of information on Git online.  

For our intended purposes, we will make use of only a very small part of Git.

First,

## How to start up git for windows?
In windows 10 type `Git bash`  in the *Type here to search* input at the lower left bottom of the Windows screen.  

![image](https://user-images.githubusercontent.com/6393033/101943757-ab11ef80-3bb9-11eb-84e0-165a031d0629.png)

Then either 
* Press the Enter key or
* click  Git Bash  (where the red checkmark appears in above image).

You should then see the 'Git bash terminal'.  Mine looks as follows, but yours will be personalized ('Anna' instead of 'Jim', for instance).

![image](https://user-images.githubusercontent.com/6393033/101944058-18258500-3bba-11eb-819f-129204108588.png)

You can type into this 'terminal' to accomplish various tasks.
First, click the mouse buttom somewhere in the terminal window.
Then, what you type will appear.   The '$' is the so-called 'prompt character', and the '|' is where the next character appears.

As a first experiment, type `git --version`   as an example of a *command*.  At this point, nothing has happened,
but now press the 'Enter' key, and the command will be *executed*.  For example,
the results of this particular command (on my machine) is `git version 2.29.2.windows.3`.
Then, my current file-system location (`Jim@Jim-Dell MINGW64 ~`) and another command prompt (`$ |`)
are printed by Git Bash.

![image](https://user-images.githubusercontent.com/6393033/101944517-d6e1a500-3bba-11eb-9438-10cb5f3fb8b3.png)


## How to get out of git terminal
Simplest is to press the 'X' close window button.

**Comment by funderburkjim** [comment]
@AnnaRybakovaT 

Are you with me so far?   When you're ready, we'll begin learning Git's role in our task  (e.g.,  corrections to cae.txt).

BTW:  What text editor do you use?

**Comment by gasyoun** [comment]
> BTW: What text editor do you use?

I can teach her EmEditor.

**Comment by AnnaRybakovaT** [comment]
Dear all,

I use Windows 7 and EmEditor.

**Comment by AnnaRybakovaT** [comment]
Jim, 
Thank you for such detailed explanations. I have installed Git and from Monday I am ready to begin learning

![image](https://user-images.githubusercontent.com/74726889/101990398-e7c41080-3cb7-11eb-83a5-774c457d853e.png)

**Comment by AnnaRybakovaT** [comment]
![image](https://user-images.githubusercontent.com/74726889/101990622-ecd58f80-3cb8-11eb-9bac-b89406f363b9.png)

**Comment by drdhaval2785** [comment]
Hi Anna,
Till Jim comes back with his exhaustive notes, you can have a look at the following link and fiddle a bit.
https://jarv-is.cdn.ampproject.org/v/s/jarv.is/notes/how-to-pull-request-fork-github/amp.html

In principle, there would be following activities.
1. Go to  https://github.com/sanskrit-lexicon/csl-orig and create a fork by clicking on 'fork' button. 
2. This will create your very own copy of the csl-orig repository as it stands now. It will be at some place like https://github.com/AnnaRybakovaT/csl-orig or something similar. You can play with it without fear of breaking anything.
3. Open 'git bash'
4. Type 'git clone https://github.com/sanskrit-lexicon/csl-corrections.git' and enter.
5. This should download your copy of csl-orig.
6. You should make necessary corrections in ap90.txt file in editor of your choice.
7. In git bash type 'git add .'
8. 'git commit -m "ap90 changes"'
9. 'git push origin master'
10. This will push all changes you made in your computer to 'AnnaRybakovaT/csl-orig' repository.
11. Open https://github.com/sanskrit-lexicon/csl-orig
12. You will see some option on the screen to 'Create a Pull Request' . Click on it. This will create a pull request.
13. Jim will look at the changes you made and approve the pull request. Then these changes become part of sanskrit-lexicon/csl-orig repository

**Comment by funderburkjim** [comment]
@drdhaval2785 and @AnnaRybakovaT    Note change in item 4 of Dhaval's instructions above.

I prefer to start with a slightly more elementary approach than the one Dhaval suggests.   
My ~~exhausting~~ exhaustive notes continue below.

@AnnaRybakovaT   Your screen shot proves you've got 'git bash' installed.   
And probably EmEditor is a good choice, since Marcis recommends.  Windows 7 should be fine for this work.

**Comment by funderburkjim** [comment]
## Preparation by Jim
I did the following in preparation for @AnnaRybakovaT to work on corrections to cae.
1. Made a 'Corrections' team for sanskrit-lexicon organization:  https://github.com/orgs/sanskrit-lexicon/teams/corrections/
2. Currently @funderburkjim  and @AnnaRybakovaT are the members of the team
3. Currently https://github.com/sanskrit-lexicon/CAE is the only repository associated with the team.
4. The members of the team have *write* privileges for the repository.

It is my understanding any 'owner' of the sanskrit-lexicon organization can make changes to the above settings.

Next, how to work with the cae repository for our current purpose.

**Comment by funderburkjim** [comment]
## A useful 'trick' to copy-paste into Git Bash

Many of the instructions following will involve 'typing' certain things into the GitBash terminal.
Some of these things are rather long to type, and there is a shortcut where you 'copy' text from a comment
and 'paste' it into GitBash terminal.

1.  Open GitBash terminal
2.  copy this text:   `git config --global --list`    
    * i.e. 'select' the text in the usual way, and then use 'Ctrl-C' to 'copy' it 
3. Click in your GitBash terminal
4. Use the key-combination  `Shift-Insert` 
    The result will be that what you just 'copied' will be 'pasted' into the GitBash prompt.
    Finally, press 'Enter', and the command will be executed.
    On my computer, it looks like:
    ![image](https://user-images.githubusercontent.com/6393033/101996493-efc48600-3ca0-11eb-899e-928dd230ff07.png)

**Comment by funderburkjim** [comment]
## 3 configuration settings for git
Notice those three global configuration settings that are marked above.
You should set these on your computer

1. Open GitBash terminal.
2. For user.name, use your Github user name (instead of X) in
   * `git config --global user.name X`
3. For user.email, use the email associated with your Github user name (instead of Y) in 
    * `git config --global user.email Y`
4. Finally, we need to be sure the Windows way of ending lines of text  doesn't interfere
   with the Unix way of ending lines of text.  This is done by:
   `git config --global core.autocrlf true`

## Another useful GitBash trick
If you double-click on some connected text in GitBash terminal,  then that
    text is 'copied' to the Windows clipboard.   You can then 'paste' that text somewhere else (using Ctrl-V).

**Comment by funderburkjim** [comment]
## cloning CAE repository
You may want to glance at this repository as it looks at Github: 
  https://github.com/sanskrit-lexicon/cae/

We want to 'copy' the repository at Github to your local machine;
We will do this 'copying' in a particular way, which is called 'cloning' 

This also is a preparation step, which you only need to do once.

1. Open 'git bash'
2. `cd ~/Documents/`   
   * You don't have to put your work in the Documents folder of Windows,  but I'll assume that you do.
3. `mkdir sanskrit-lexicon`   ## we'll further assume all work done in the 'sanskrit-lexicon'
4. `cd sanskrit-lexicon`
5. `git clone git@github.com:sanskrit-lexicon/CAE.git`
    * You will see this in your terminal:
    ```$ git clone git@github.com:sanskrit-lexicon/CAE.git
     Cloning into 'CAE'...
     remote: Enumerating objects: 68, done.
     remote: Counting objects: 100% (68/68), done.
     remote: Compressing objects: 100% (50/50), done.
     remote: Total 68 (delta 29), reused 52 (delta 15), pack-reused 0
     Receiving objects: 100% (68/68), 1.76 MiB | 4.94 MiB/s, done.
     Resolving deltas: 100% (29/29), done.
     ```

You can do a preliminary comparison with what is on Github.
In Gitbash:  
` cd CAE`
` ls`   # lists files in CAE.

Etc.
You can also use the normal Windows Explorer way of looking at files.
In Windows 10, this looks like:
![image](https://user-images.githubusercontent.com/6393033/101998786-62833080-3ca4-11eb-995c-0c4ad150ec92.png)

**Comment by funderburkjim** [comment]
## Batch 1 of CAE corrections: Step a

These instructions will walk through doing a small first batch of corrections to your local CAE repository,
and then pushing those corrections back up to Github.

This step does not use GitBash.

1. In Windows Explorer, open the `english_corrections` folder.
    * Open cae_error1.txt in your text editor  (EmEditor) 
    * Be sure of utf-8 encoding, by EmEditor  File/Reload/UTF-8
2. Similarly open cae.txt
3. Enable two horizontal windows by EmEditor/Window/Tile Horizontally
4. Resize EmEditor windows as convenient.
5. In a Browser, open a display of CAE 

Here's how my desktop looks at this point:

![image](https://user-images.githubusercontent.com/6393033/101999119-bb07fd00-3ca7-11eb-8b08-217141ba66ab.png)

**Comment by funderburkjim** [comment]
## Make some changes

First, insert a comment at top of cae_error1.txt: `; Batch 1`

The first item of cae_error1.txt looks is '95:akfpaRa:unquerulous:'

unquerulous is probably ok, although archaic.  So mark it as 🆗 `95:akfpaRa:unquerulous:OK` in cae_error1.txt

You can add comments by inserting an extra line following the item and starting that line with a semicolon.
e.g.
```
95:akfpaRa:unquerulous:OK
; probably archaic
```

But you don't have to make a comment for every line.  Just when you think it is important.

You could look at the corresponding word in cae.txt.
By finding 'L>95'  in cae.txt.
```
<L>95<pc>002<k1>akfpaRa<k2>akfpaRa
{#akfpaRa#}¦ <lex>a.</lex> unquerulous, cheerful.
<LEND>
```
You also could look at the display:
![image](https://user-images.githubusercontent.com/6393033/101999278-64032780-3ca9-11eb-9498-b0fba7efdecf.png)

and you could further check the scanned image, by clicking the link in the above display.

You could do a Google search on 'define unquerulous'.

All these things you *could* do.  It's up to you what you *should* do in any given case.

Now let's take an example where a spelling change looks necessary: `304:aNga:sollicitation:`.

```
<L>304<pc>005<k1>aNga<k2>aNga/<h>1
1 {#aNga/#}¦ <lex>a.</lex> particle implying sollicitation, confirmation, or
stress.
<LEND>
```
In this case, the scanned image also shows `sollicitation`, but this is surely
wrong.  It should be `solicitation`.  
So change cae_error1.txt to
```
304:aNga:sollicitation:solicitation
; scan error
```
It's useful to make the '; scan error' comment since our change will 
cause an intentional difference between our digitization and the original printed text;
and I will make a note of that in the appropriate place when I install the corrections

And, of course we need to make the change in cae.txt:
```
1 {#aNga/#}¦ <lex>a.</lex> particle implying solicitation, confirmation, or
```

## A first trial run
Examine the first several (10-20) items in cae_error1.txt, mark them up 
in cae_error1.txt and, where needed, in cae.txt.

Then save both files cae_error1.txt and cae.txt.

When this is done, you're ready to commit the changes to git, and push the results to Github.
That's described in next comment.

**Comment by funderburkjim** [comment]
## Committing the change

You've done a Batch of changes, saved cae.txt and cae_error1.txt,
and are ready to communicate the changes so I can see them.

This work is done in the GitBash terminal.

##  check which files have changed (optional)
Use the Git status command.
```
Jim@Jim-Dell MINGW64 ~/Documents/sanskrit-lexicon/CAE (master)
$ git status 
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   english_corrections/cae.txt
        modified:   english_corrections/cae_error1.txt

no changes added to commit (use "git add" and/or "git commit -a")
```

## Check the changes in a file (optional)
Use *git diff* command:
```
Jim@Jim-Dell MINGW64 ~/Documents/sanskrit-lexicon/CAE (master)
$ git diff english_corrections/cae.txt
diff --git a/english_corrections/cae.txt b/english_corrections/cae.txt
index 4280ab4..db56e7b 100644
--- a/english_corrections/cae.txt
+++ b/english_corrections/cae.txt
@@ -1291,7 +1291,7 @@ criminal).
 <LEND>

 <L>304<pc>005<k1>aNga<k2>aNga/<h>1
-1 {#aNga/#}¦ <lex>a.</lex> particle implying sollicitation, confirmation, or
+1 {#aNga/#}¦ <lex>a.</lex> particle implying solicitation, confirmation, or
 stress.
 <LEND>


Jim@Jim-Dell MINGW64 ~/Documents/sanskrit-lexicon/CAE (master)
```
If there were many changes,  the last line might show as ':' .  
Then type 
* [space-bar] to see more changes, 
* or letter 'q'  to quit seeing more output from 'git diff'

##  prepare to commit the changes
This is the git add command:
```
$ git add .

Jim@Jim-Dell MINGW64 ~/Documents/sanskrit-lexicon/CAE (master)
$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        modified:   english_corrections/cae.txt
        modified:   english_corrections/cae_error1.txt


Jim@Jim-Dell MINGW64 ~/Documents/sanskrit-lexicon/CAE (master)
```

`git add .`  doesn't output anything.
So I often follow it with 'git status', to be sure that everything was added as I expected.

##Next, commit
`git commit -m "a comment briefly describiing the commit, such as 'Batch 1 English Corrections"`

**Comment by funderburkjim** [comment]
## Push the changes to Github
In GitBash,  
```
git push
```

This gives some arcane output.
I didn't want to push my changes to CAE, so I can't show you exactly what the output looks like.

##  Make a note in the #25
I've made a separate issue for the actual work of CAE English spelling corrections.
Make a comment there when you've pushed a Batch of changes. That comment
will alert me there is another batch of corrections for me to review and install.

We can also use #25 to discuss specific correction questions that may arise as
you are doing batches.

##  Remaining batches

You can break up the work into batches of any size you want.  Sampada usually
uses batches of 50-100.  

Your work on a batch can be done in several editing sessions.  For instance you 
might have time one day to work on 10 items from cae_error1.txt,  another day 30, etc.
Just save your files.  Then, when you've got enough for a reasonable sized batch,
do the 'git add', `git commit`, `git push` , `#25 comment` steps to publish the batch.

**Comment by gasyoun** [comment]
> My exhausting exhaustive notes continue below.

I love you both, guys, Jim and Dhaval. And I'm impressed by the tech level of Anna.

**Comment by funderburkjim** [comment]
@AnnaRybakovaT   I think the above covers the steps.
But of course, raise any questions/problems as needed.

Good luck!

**Comment by funderburkjim** [comment]
> desktop.github.com

I don't use that, so don't know for sure.  It might very well provide a viable alternate workflow to the 'GitBash' approach.

**Comment by drdhaval2785** [comment]
Github Desktop for windows hangs once the changes are above 500 lines or so, which is quite possible in our repositories. I think the GUI gets too busy creating the visible diff. 
Not a viable option for repos getting large changes.

**Comment by gasyoun** [comment]
>  windows hangs once the changes are above 500 lines

@AnnaRybakovaT can keep it as 100 at once easily.

**Comment by AnnaRybakovaT** [comment]
> When this is done, you're ready to commit the changes to git, and push the results to Github.

Dear Jim,
I have followed all above commands.
Tommorow I will examine some items and will try to commit the changes to git and push the results to Github.

**Comment by AnnaRybakovaT** [comment]
![image](https://user-images.githubusercontent.com/74726889/102121397-fd227180-3e54-11eb-96d5-bbdd70c7a322.png)

![image](https://user-images.githubusercontent.com/74726889/102121436-090e3380-3e55-11eb-84f4-34446d79136b.png)

![image](https://user-images.githubusercontent.com/74726889/102121479-14f9f580-3e55-11eb-9c69-21d9d7d34e59.png)

**Comment by AnnaRybakovaT** [comment]
![image](https://user-images.githubusercontent.com/74726889/102121530-28a55c00-3e55-11eb-916a-b8afc6be00e8.png)

![image](https://user-images.githubusercontent.com/74726889/102121537-2c38e300-3e55-11eb-98a5-384b222554d7.png)

**Comment by AnnaRybakovaT** [comment]
I would like to pay attention on one item.
When I did cloning the repository at Github to my local machine I typed:
"git clone https://github.com/sanskrit-lexicon/CAE"
since when before I had used 
"git clone git@github.com:sanskrit-lexicon/CAE.git"
cloning was not done.
![image](https://user-images.githubusercontent.com/74726889/102121740-83d74e80-3e55-11eb-9ffa-44d64922a6d4.png)

I suppose it doesn't matter since in any case the cloning has done.

**Comment by funderburkjim** [comment]
Your screen shots show things are fine so far.

You mentioned a question:

> "git clone git@github.com:sanskrit-lexicon/CAE.git" didn't work.

I just checked, and this does work on my computer.
Maybe there is something in my GitBash  that I didn't realize.

I agree that it doesn't matter much, since your method did allow the clone.

##  experiment (optional)

Make some file ,  maybe call it 'anna.txt' in english_corrections in your local computer,
and put some message in it  ('this is a test', or whatever)

Then in GitBash, stage/commit/push
```
git status  # check your file shows up in red
git add .   # stage all changes
git status # check your file shows up in green
git commit -m "Add anna.txt"    #  a brief description of the git commit
git status   #  on branch master ....
git push
```

See if your push works ok.

Go to github, and convince yourself your file is there.

If you are already in the midst of changes to cae.txt on local computer,
you can skip this experiment, or do it later.

**Comment by AnnaRybakovaT** [comment]
> When this is done, you're ready to commit the changes to git, and push the results to Github.

Dear Jim,
thanks to your detailed instructions, this operation has done.
![image](https://user-images.githubusercontent.com/74726889/102257869-586c6680-3f1e-11eb-82f1-bf3c8655d0a1.png)

**Comment by AnnaRybakovaT** [comment]
> you can skip this experiment, or do it later.

I understood how to do it. 
I had wanted to do this experiment together with the Batch 1 but I  changed my mind and deleted the new file. I will do it tomorrow to close this topic. (since I have to finish work and leave now).

**Comment by gasyoun** [comment]
> I understood how to do it.

Anya has become more advanced in no time as me ))

**Comment by AnnaRybakovaT** [comment]
> See if your push works ok.

Dear Jim,
The file anna.txt is in the repository. 
![image](https://user-images.githubusercontent.com/74726889/102341706-42f04e80-3fa9-11eb-99a5-9c02580cf31d.png)

So I can start analizing the errors and when the first 100 lines are ready, I will push the next Batch of changes. I will make a comment in the issue #25.

**Comment by AnnaRybakovaT** [comment]
> Anya has become more advanced in no time as me ))

Only thanks to magic instructions Of Jim!

**Comment by funderburkjim** [comment]
## line-endings 


This comment pertains to that instruction `git config --global core.autocrlf true`  above.

I now think that it should have been set as `git config --global core.autocrlf input`  

@AnnaRybakovaT   Please just read the following, but DON'T do any changes to your
git configuration now.  Otherwise, keep doing batches just as you did the first batch.

## Why is 'core.autocrlf true' a problem?

The issue of line endings is a subtle issue, because it is usually 'invisible'.

To demarcate what is a 'line' in a text file,  various text editors and operating systems have
different conventions.    

Usually, a text editor on a Windows computer will use a two-ascii-character sequence identified
as CRLF  (carriage-return  line-feed).

Usually, a text editor on a Linux computer will use the one-ascii-character identfied as LF (line-feed).

For our project,  we have a mixture of computers.
*  Cologne server is a Linux computer
*  Many of our local computers are Windows computers.

*Our 'official' form of line-endings for files  (such as cae.txt) is that of Cologne server, namely LF.*

This means that the official form stored in our Git repositories (notably csl-orig repository)
has Unix line endings.

The cae.txt file in sanskrit-lexicon/cae/english_corrections was originally created by me as a copy from my local version of csl-orig/v02/cae/cae.txt and it had Unix line endings;  
> I think it did.  I am not absolutely sure.

However, when, after anna's push,  I pulled sanskrit-lexicon/cae/english_corrections,  the
file cae/english_corrections/cae.txt appears to have CRLF line endings.  For instance, the
GitBash 'diff' command to compare `cae/english_corrections/cae.txt` with
`csl-orig/v02/cae/cae.txt` shows  that EVERY line is different.  Further investigation
shows that the reason is that every line of `cae/english_corrections/cae.txt` ends with CRLF.


This difference is not due to anything that Anna did wrong.

Also, I have a small python program that can change CRLF to LF; so can work with
the `cae/english_corrections/cae.txt` as it now exists.

As I said above, I think it is that the config should have been set
as `git config --global core.autocrlf input` ;  in fact, I think that is the way I originally had
my computer configured, and is the way my computer is now configured.

When Anna finishes the batches of corrections for CAE,  I'll try to develop a controlled 
experiment so that this problem will disappear for us in the future.

**Comment by gasyoun** [comment]
> Also, I have a small python program that can change CRLF to LF; so can work with
the cae/english_corrections/cae.txt as it now exists.

What's the name and where it lies?

> When Anna finishes the batches of corrections for CAE, I'll try to develop a controlled
experiment so that this problem will disappear for us in the future.

Oh, ok.

**Comment by AnnaRybakovaT** [comment]
> Please just read the following, but DON'T do any changes to your
> git configuration now. Otherwise, keep doing batches just as you did the first batch.

OK

**Comment by drdhaval2785** [comment]
Now we have Anna running the git / github show. So, closing this issue. 
We can direct any new entrant to this issue, if need be.

**Comment by gasyoun** [comment]
> We can direct any new entrant to this issue, if need be.

Yes, but I will try to make Usha do it the Desktop way in SKD.
