### ISSUE TITLE
extend Lanman dictionary refs to Reader

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-corrections#24]
Consider this preliminary application for the Lanman reader: https://funderburkjim.github.io/lanman/reader/index2.html

Click on story 13: The blue jackal.
![image](https://user-images.githubusercontent.com/6393033/101968944-cef02800-3bef-11eb-8d80-c8a8825bc747.png)

Notice:
* For the first line of the story, there is only one word with a dictionary reference, भ्रम्.
* However, consider the 4th word of this line, नगरोपान्ते.  which has uninflected base नगरोपान्त.  
   This word IS in the Lanman dictionary:  https://www.sanskrit-lexicon.uni-koeln.de/simple/lan/नगरोपान्त 

Why isn't there a link to नगरोपान्त in the reader, in addition to भ्रम्.  And similarly for other words in that
line of the reader?

**Comment by funderburkjim** [comment]
The basic answer is that Lanman's vocabulary gives only SOME links back to the reader.

For instance, the dictionary entry for भ्रम्  https://www.sanskrit-lexicon.uni-koeln.de/simple/lan/भ्रम्  
has a back reference to line 12 of page 36, which is the line of the reader we are using in this example;
and there is also a reference to line 5 of page 23.

![image](https://user-images.githubusercontent.com/6393033/101969252-643fec00-3bf1-11eb-96d8-f9fd45dff44d.png)

However, the entry for नगरोपान्त has no links to the reader at all:
![image](https://user-images.githubusercontent.com/6393033/101969339-e03a3400-3bf1-11eb-9b83-148a90080458.png)

**Comment by funderburkjim** [comment]
The proposal of this issue is to augment the dictionary by adding additional links from the dictionary back to the
reader.  

This will be done in such a way that the augments can be identified as not in the original digitization, but are
otherwise similarly coded as the original dictionary links to the reader.

The current dictionary markup in lan.txt for the link for bhram is
```
<ls n="lan,36,12">36<sup>12</sup></ls>
```

The entry for nagaropānta in lan.txt is currently:
```
{@nagaropānta,@}¦ {%<ab>n.</ab>%} neighborhood of the
town. [{@upānta.@}]
```

One proposed change would be
```
{@nagaropānta,@}¦ {%<ab>n.</ab>%} neighborhood of the
town. [{@upānta.@}]  <ls n="lan,36,12,x">36<sup>12</sup></ls>  
```
where ',x' has been added as a 3rd parameter, where we are using 'x' to remind us that this is an 'extra'  link
to the reader.

**Comment by funderburkjim** [comment]
## How to find those extra links.

A program should be able to do at least some of an initial augmentation.

For instance, we can first consider all words X in the dictionary which currently have NO link, such as
X = nagaropAnta.   

For such an X, we can remove the final vowel and search all the lines of the reader for the string 'nagaropAnt'.
When we find such a line, we can note the page number and linenumber on that page and construct
our link, and then add that link to the dictionary entry for X in lan.txt.

This seems like a reasonable and doable first approximation.  Let's try it and see how many new links we get,
and if they are correct.

**Comment by funderburkjim** [comment]
Note: This issue should have been in https://github.com/funderburkjim/lanman/ repository !

Sorry about that.

Have now copied to https://github.com/funderburkjim/lanman/issues/7.

**Comment by gasyoun** [comment]
> Consider this preliminary application for the Lanman reader: https://funderburkjim.github.io/lanman/reader/index2.html

What an amazing work, but is https://funderburkjim.github.io/lanman/notes/index.html#rpl_03403 CSS working as intended?

![cfw](https://user-images.githubusercontent.com/80761/101982108-bc72fe80-3c82-11eb-8b71-342745206ce0.JPG)
