### ISSUE TITLE
Improve English error code

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/csl-corrections#28]
There are some todo things for improving the code that generates English error report. Currently the next two items are giving majority of false positives.

1. Ignore `[Pagexxx]` occuring in between texts. 
2. Ignore hyphen at the end of line. It splits the word into two incomprehensible parts.
3. Analyse the output once again to find out such cases which may be giving false positives.
4. Put the code in CORRECTIONS repository.

I was waiting for Sampada and Anna to complete their work, so as regeneration does not break any workflow. 

Will execute the above in next one or two days

**Comment by gasyoun** [comment]
> Will execute the above in next one or two days

Thanks. Because this part of the work will take years even without false positives.

**Comment by drdhaval2785** [comment]
In majority of cases, the words starting with capital first letter are false positives.
They are proper names of place, person or botanical names. 
Will try to ignore them in the output, and check the result.

**Comment by drdhaval2785** [comment]
This process is now over. 
The code is available in CORRECTIONS repository at https://github.com/sanskrit-lexicon/CORRECTIONS/blob/master/english_error/find_english_errors.py

The latest output is available at https://github.com/sanskrit-lexicon/CORRECTIONS/tree/master/english_error/output
Note - ignore the run1, run2, run3 etc folders. (They are for archival purpose only.)
Use the files XXX_errors.txt files only.
