### ISSUE TITLE
WIL errors while regen

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/csl-corrections#3]
```
construct wil.xml...
  File "make_xml.py", line 27
    print "UNKNOWN DIVISION: ",x.encode('utf-8')
```

It seems that python for my computer means python3.
whereas the code is for python2.

**Comment by drdhaval2785** [comment]
@funderburkjim 
I am trying to make python codes python2 and python3 compliant.
csl-pywork would be under active changes for today and tomorrow.

**Comment by drdhaval2785** [comment]
https://github.com/sanskrit-lexicon/csl-orig/commit/fd18a4bbbfcf59c168e25271bd466d0db4f5355e closed this issue.

**Comment by funderburkjim** [comment]
Glad you discovered that -- I was not sure how to do python3 test for csl-pywork.
Please notify me when csl-pywork conversion complete.

**Comment by drdhaval2785** [comment]
Conversion done. You may pull

**Comment by funderburkjim** [comment]
Got it  - thanks.

You probably should similarly review other 'csl-' repositories -- at the moment, I'm not sure whether there is python code in any of them. Such as csl-websanlexicon.

**Comment by funderburkjim** [comment]
@drdhaval2785   I pulled and ran on local computer for pwg -- my 'python' is python2,
so we have evidence that the programs work on python2 and python3 .  A big step!

I also pulled to Cologne, and, as expected the update to pwg worked fine.
