### ISSUE TITLE
MW english errors

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/csl-corrections#30]
Continuing the corrections based on #14 method.

@AnnaRybakovaT may like to check up the potential errors in the Monier Williams dictionaries next, as this is the most widely used dictionary in Sanskrit-English genre.
https://github.com/sanskrit-lexicon/CORRECTIONS/blob/master/english_error/output/mw_error.txt has 110 lines of suspect words.

Anna and Jim may continue to post batches of this dictionary here.

**Comment by gasyoun** [comment]
> as this is the most widely used dictionary in Sanskrit-English genre.

It sure remains.

**Comment by AnnaRybakovaT** [comment]
> 110 lines of suspect words.

With pleasure I am ready to analyze the Monier Williams dictionaries and start from this list of errors.

As I see - I will need some files- like mw.txt and mw_error1.txt

**Comment by drdhaval2785** [comment]
mw.txt or any dictionary text file should be available at https://github.com/sanskrit-lexicon/csl-orig/tree/master/v02 

For specific mw.txt, it is available at https://github.com/sanskrit-lexicon/csl-orig/blob/master/v02/mw/mw.txt

**Comment by AnnaRybakovaT** [comment]
> For specific mw.txt, it is available at https://github.com/sanskrit-lexicon/csl-orig/blob/master/v02/mw/mw.txt

I see, thanks

**Comment by gasyoun** [comment]
> 7718:anUdaka:metri,causa

Should we mark non-English text, as this Latin `metri causa` with some tag, @funderburkjim ?

**Comment by funderburkjim** [comment]
@drdhaval2785 and @AnnaRybakovaT 

Wait a minute ---   I prefer that @AnnaRybakovaT   does NOT change the csl-orig repository.  

 >Reason:  @drdhaval2785 and @funderburkjim  should be gate-keepers for csl-orig.


Let's follow the CAE model:   Namely work with a separate copy of mw.txt in the
MWS repository.   

Detailed instructions for Anna  
* git clone git@github.com:sanskrit-lexicon/MWS.git
* Use mw_error1.txt in folder mwtranscode/english_corrections
* Make corrections to local file mwtranscode/mw.txt and comments to local file mw_error1.txt
* Push changes for a batch to mws repository 
* Notify me  in a comment in this issue when a new batch is made.
   * Then my task will be to review and integrate changes into csl-orig/v02/mw/mw.txt

**Comment by funderburkjim** [comment]
> Should we mark non-English text ... ?

Anna made some notes of this type in [cae_error1.txt](https://github.com/sanskrit-lexicon/CAE/blob/master/english_corrections/cae_error1.txt).   
I think these were good to have,  and similar comments in mw_error1.txt would also be good.

However, it is premature to add markup to cae.txt or mw.txt  in such cases, IMHO.

**Comment by drdhaval2785** [comment]
I understand @funderburkjim's concern about he and I being gatekeepers of sanskrit-lexicon/csl-orig repository.

I have written a tutorial for @AnnaRybakovaT and any future volunteer who wants to submit corrections frequently at #31 .
Maybe Anna can give it a try for one correction and let me know if she succeeded in making a pull request.
If it proves too difficult, we may drop this idea.

Now because we are on git based workflow, let us try to maximize its potential. In our case, 'Pull Request' feature will take care of most of our problems.

**Comment by gasyoun** [comment]
> However, it is premature to add markup to cae.txt or mw.txt in such cases, IMHO.

You're the boss.

> Maybe Anna can give it a try for one correction and let me know if she succeeded in making a pull request.
If it proves too difficult, we may drop this idea.

Still let hem give a try.

> Now because we are on git based workflow, let us try to maximize its potential. 

Agree.

**Comment by AnnaRybakovaT** [comment]
> Let's follow the CAE model: Namely work with a separate copy of mw.txt in the
> MWS repository.

Dear Jim,
According to instruction I have made git clone. Everything is clear.

**Comment by AnnaRybakovaT** [comment]
> Maybe Anna can give it a try for one correction and let me know if she succeeded in making a pull request.

Dear all,
Please let me know if and when can I try to do it.

**Comment by drdhaval2785** [comment]
Dear Anna,

Let me be very clear about the processes.

Process 1 - The way you coordinated with Jim for CAE corrections.

Process 2 - The method mentioned at https://github.com/sanskrit-lexicon/csl-corrections/issues/31 for pull request generation by me.

Both are separate ways to do the same work.

You may try instructions in process 2 for a single correction for now, and let me know the feedback. Once you succeed in it, you can make 20-30 corrections in one go and add, commit, push and create a pull request. 

In this case, Jim or I would not have to do any manual work other than just looking at your changes visually and merge it.

**Comment by AnnaRybakovaT** [comment]
> You may try instructions in process 2 for a single correction for now,

OK. I will try to make a single correction today and after I will let you know the feedback.

**Comment by gasyoun** [comment]
> In this case, Jim or I would not have to do any manual work other than just looking at your changes visually and merge it.

And that would save the valuable hours we do not have anyway.

**Comment by AnnaRybakovaT** [comment]
> Process 2 - The method mentioned at #31 for pull request generation by me.

Dear all,
The first "test" pull request has created.
I did'not notice any problems. 
At step 6.7 - the programm didn't ask me username and password.
Sinse the error from instruction was corrected, I used this line - 2076:anucita:unusaul -> unusual

**Comment by drdhaval2785** [comment]
That is a great news.
regarding non promping for password, it may be because you have already stored your credentials while setting up git and github according to #23 .

**Comment by gasyoun** [comment]
> The first "test" pull request has created.

Anya is sure quick in learning. Long live Cologne dictionaries!

**Comment by funderburkjim** [comment]
@AnnaRybakovaT 

> According to instruction I have made git clone. Everything is clear.

For these MW corrections,  let's following Process1  (use MWS repository,  same model as CAE).

For the next one  (pui),  we'll  try it  with Dhaval's Process2.

**Comment by AnnaRybakovaT** [comment]
> For these MW corrections, let's following Process1 (

Dear Jim,

The Batch 1 is ready. The all list of MW errors has analyzed.

I am waiting for new instructions.

**Comment by gasyoun** [comment]
> I am waiting for new instructions.

Is not she cute? We need to have a list, otherwise she is quicker than we can actually manage.

**Comment by funderburkjim** [comment]
## MW corrections from Anna
```
mw_error1.txt
114:aMh:conjecturable: OK
; alternative form is "conjectural"
1390:aGfRa:incompassionate: OK
; alternative form is "uncompassionate"
3928.1:adviyoni:diphthongal: OK
4215:aDikzip:superinduce: OK
4322:aDimukta:propense: OK
; archaic, synonyms "disposed", "prone"
5244:anarSarAti:uninjurious: OK
5370.1:anavIkfta:motonony: monotony
; scan error
6342:anutap:desiderate: OK
6677:anupalakzita:indiscriminated: indiscriminate
; scan error
7013:anumfj:lengthways: OK
; alternative form is "lengthwise"
7718:anUdaka:metri,causa: OK (Latin phrase translated as "for the sake of the metre")
7732:anUDas:udderless: OK
9166:apatantra:emprosthotonos: OK (medical term)
9591.1:aparisaMKyAna:diffcrence: difference
9719:apavfj:carpere,viam: OK (Latin phrase translated as "take a path")
10630:apratIta:unattackable: OK
13201:aByanumud:necess: OK (necess.)
13591.1:aByunmodanIya:aquiesced: acquiesced
; Scan error
14559:ambUkfta:onomatopoetically: OK
; alternative form is "onomatopoeically"
14599:amBiRI:preceptress: OK
17032:avakrand:cakradat: OK (Sanskrit word, mw.txt is corrected)
17259.1:avajAta:misborn : OK
; rare, synonyms "illegitimate", "aborted", "prematurely born"
17749:avaBuj:incurve: OK
19778.4:aSmaSru:unbearded: OK
20882:asADAraRa:specifical: OK
; alternative form is "specific"
20918.1:asAhacarya:unsimultaneousness: OK
; synonym "asynchrony"
21282.1:astarya:unconquarable: unconquerable
22494.1:AKedana:drawlng: drawing
23282:AQaka:avds: OK (Avds. - an abbreviation of "Avoirdupois")
; maybe to write the whole word "Avoirdupois"
; jim: change to <ab n="avoirdupois">avds.</ab>' -- the markup for
;   a local (rarely occurring) abbreviation.
24543:AnIla:darkish: OK
24677:Anemimagna:felloe: OK
25270:ABicaraRika:maledictory: OK
26630:Arza:archaistic: OK
; alternative for is "archaic"
28129:AstuB:huzza: OK
28747:iti:caetera: OK (et caetera - Latin expression "etc")
29387:irya:energetical: OK
; alternative form is "energetic"
29421:ilISa:hilsa: OK (fish)
34200:upakxp:asign: assign
; scan error
34860:upanaKa:agnail: OK
; alternative form is "hangnail"
35490:uparam:quietist: OK
36010:upasaMviS:environ: OK
36634:upAtaNkya:runnet: OK
; alternative form is "rennet"
43621:kapiYjala:heathcock: heath-cock
; jim:  leave as 'heathcock'
43621:kapiYjala:francoline:francolin
; scan error
; jim  Anna changed but did not mention.
49636:kAlambya:caravansery: OK
; alternative forms are "caravansary", "caravanserai"
51432:kucika:apterygia,synbrache: OK (Muraena)
51450:kuYc:frounce: OK
; archaic
51760:kuqUhuYcI:trilobatum: OK (Solanum trilobatum - herb)
; I have corrected mw.txt -  this word is highlighted
; jim: Anna improved 'bot' markup from
;    '<bot>Solanum</bot> trilobatum' to '<bot>Solanum trilobatum</bot>'
51788:kuRajI:orach: OK (plant)
52647:kuraNkara:sibirica: OK (Ardea sibirica - bird)
53501:kuzWa:arabicus: OK (Costus arabicus - plant)
; I have corrected mw.txt - this word is highlighted
; jim: Anna's change:
;  old '<bot>Costus speciosus</bot> or arabicus'
;  new '<bot>Costus speciosus</bot> or <bot>arabicus</bot>'
54922:kfpIwa:underwood: OK
55571:kxp:subserve: OK
56567:koTarI:opuntia
; jim: Added bot markup: '<bot>Cactus opuntia</bot>'  
57749:kram:appliable: OK
; obsolete, synonyms "applicable", "compliant"
59502:kzip:outvie: OK
; archaic
64967:gArzweya:proparox: proparox.
; abbreviation for "proparoxytone". maybe to write the whole word "proparoxytone"
; jim: We have 'proparox.' in mw abbreviations (such as under jAtarUpa).
; It is not marked as abbreviation here, in gArzweya. Added that markup
; '<ab>proparox.</ab>'
70136:GeYculikA:orixense: OK (Arum orixense - plant)
; I have corrected mw.txt - this word is highlighted
; jim: Anna's change: 'Arum orixense' -> '<bot>Arum orixense</bot>'
72674:calu:monthful: mouthful
75341:cyut:lixiviate: OK
; I didn't find this word in the scan
; jim:  Found it near bottom of col.3 of page 403.
; see https://sanskrit-lexicon.uni-koeln.de/scans/csl-apidev/servepdf.php?dict=mw&page=403
81100:JiNgAka:acutang: acutang. (Luffa acutang. - plant)
; I have corrected mw.txt - this word is highlighted
81410:qiRqira:sepiae: OK (os sepiae - cuttlefish)
; Latin "os sepiae" is highlighted like <bio>
81499:QArikA:julus: OK (a genus of millipedes)
83643:taSlI:trigon: OK (abbreviation for "trigonometry")
; maybe to write the whole word "trigonometry"
; jim: '<ab n="trigonometry">trigon.</ab>'  since abbrev. only occurs here
93581:dunduBa:unvenomous: OK
; alternative form is "nonvenomous"
103412:nanA:fam: OK (fam. - is an abbreviation, probably for "familiar")
; jim: occurs in 5 places.  Am changing all to <ab n="familiar">fam.</ab>
104760:naS:cond: OK (conditional)
; I have corrected mw.txt
; jim:  Anna's correction is 'cond.' -> '<ab>cond.</ab>'  (since 'cond.'
;  is a known abbreviation in mw.)
108041:nigam:feminam: OK (Latin phrase "inire feminam" = "inner female")
108095:nigF:ingurgitate: OK
108868:niBa:pleonast: OK (abbreviation of "pleonastic" or "pleonasm")
; it would be good to highlight "pleonast."
; jim: changed 'pleonast.' to '<ab n="pleonastically">pleonast.</ab>'
109269:niraya:egression: OK
; alternative form is "egress"
109710:nirBaj:coparceny: OK
; synonym "coparcenary"
110355:nivft:reconduct: OK (conduct back)
136064:pramohin:xxx:xxx
; jim:  noticed at line 458150 '<LEND>indeclineable' ---- this is an error!
;  <LEND> should have nothing following it.
;  Anna:  Any idea where that 'indeclineable' came from?
119683:paryavaDAraRa:subtilizing: OK
120516:paS:interjectionally: OK
127307:pU:illume: OK
; synonym "illuminate"
128944:petva:wether: OK (a castrated ram)
129097:pEcCilya:mucilaginousness: OK
134208:pratyADmAna:tympanites: OK (illness)
136065:pramUtrita:urined: urinated
; jim:  Changed back to 'urined': 
; from http://www.webstersdictionary1828.com/Dictionary/Urine
; urine could be a verb;  current synonym would be urinate.
142181:PiwsUtra:grammat: OK (abbreviation, I suppose for "grammatical")
; jim: changed 'grammat.' to '<ab n="grammatical">grammat.</ab>'
151456:BU:indeclineable: indeclinable
; jim: scan has 'indecl.', occurs 3 times in mw.
;  'indeclineable' -> '<ab n="indeclinable">indecl.</ab>' to agree with scan
; changing other two 'indecl.' similarly
157954:manyA:musculus,cucullaris,trapezius: OK (Latin names of muscles)
; I have corrected mw.txt -  highlighted those words
; jim: Anna's correction was 
; old: <bio>musculus</bio> cucullaris or trapezius
; new: <bio>musculus cucullaris</bio> or <bio>trapezius</bio>
; '<bio>' tag reserved for scientific names of animals.
; These words are Latin names of anatomical parts.
; So, the original '<bio>musculus</bio>' was wrong.
; We currently don't have a markup appropriate for these Latin words.
; Am changing to: musculus cucullaris or trapezius
; 
158467:marqitf:pitier: OK
158996:malha:dewlapped: OK
161632:mahalla:mahall: OK (Arabic word)
; Please check if I highlighted this word right. In mw.txt this word doesn't write by Arabic script like in the scan
; jim:  We missed this.  It should NOT be marked with <s>
; Rather it should be like 
; <lang script="Arabic" n="Hindustani">ارهٿ</lang>   (hw = araGawwa)
; Am changing back to the way it was.  We'll have to get help for the
; arabic from jsonreeder (see 
; https://github.com/sanskrit-lexicon/ArabicInSanskrit/issues/15 )
165844:murBiRI:firepan: OK
168975:ya:bacchic: OK (in Prosody kind of simple feet - consists on one short syllable and two long)
170148:yad:directa: OK (Latin "oratio directa" translating as "direct speech")
170842:yavya:andcol: and col.
; maybe instead of "and" to use ",". In this case - See p.847, col.1. 
; jim: OK to leave 'and'
171539:yAvat:quantus: OK (Latin word, translated as "how")
181883:lavaRa:brinish: OK
; synonym "saltish"
191846:vArkza:arboreous: OK
; synonym "arboreal"
194107:vikxp:optionable: OK (Meaning that there are several options)
196817:vinam:cerebralize: OK
; alternative form is "cerebralise"
203329:vI:conjug: OK (abbreviation, connected with "conjugate")
; jim: only occurrence of this abbreviation. Changing
; 'conjug.' to '<ab n="conjugational">conjug.</ab>'
; I think the term 'conjugational tenses' refers to the present, imperfect,
; optative and imperative tenses whose conjugation tables are based on the
; conjugational class (1,2, ..., 10).
204309:vfj:abalienate: OK
; synonym "alienate"
205598:vettf:espouser: OK
206784:vEjAtya:heterogeneousness: OK
; synonym "heterogeneity"
206930:vEtraka:cany: OK
; synonym "reedy"
215596:SAmAka:incorr: OK abbreviation, but I have doubt - for which word)
; jim:  abbreviation 'incorr.' occurs 3 times in mw, but none are marked.
; Am marking all three as '<ab n="incorrect">incorr.</ab>'
215849:SArNga:corneous: OK
225974:saMvac:nonconj: OK (abbreviation, connected with "non-conjugate")
; "the nonconj. Tenses" - should be "the nonconj. tenses". I don't know - how to correct it.
; jim:  'nonconj.' occurs just once. Changing to
;  <ab n="non-conjugational">nonconj.</ab>
; The non-conjugational tenses are perfect, future, etc.
242131:sApta:heptade: OK (group of seven)
242167:sABinayam:pantomimically: OK
245120:sIm:cunque: OK (Latin word)
; better to  italicize this word (I don't know how to do it)
; jim:  Disagree with italics, as it is not italic in scan.
;  We don't currently have an established markup for Latin words.
251413:sUpasidDa:relishable: OK
252008:sfp:bended: OK
; archaic, a modern form is "bent"
252367:seSvara:theistical: OK
; synonym "theistic"
252716:soma:trinkled: OK
; dialectal, synonym "trickled"
253966:sOvastika:benedictive: OK
; synonym "benedictional"

EXTRA
43621:kapiYjala:francoline: francolin 
; scan error, "francolin partridge" - a bird
; jim: Thanks for mentioning the extra correction.

```


@AnnaRybakovaT  Please note several comments, and discuss further any of my changes as you see fit.

**Comment by gasyoun** [comment]
> 'incorr.' occurs 3 times in mw, but none are marked.

Should not we?

**Comment by AnnaRybakovaT** [comment]
> 136064:pramohin:xxx:xxx
> ; jim:  noticed at line 458150 '<LEND>indeclineable' ---- this is an error!
> ;  <LEND> should have nothing following it.
> ;  Anna:  Any idea where that 'indeclineable' came from?


I am sorry, It was my mistake, just I have pasted this word in mws.txt by mistake.. 
This word connected with this line:
151456:BU:indeclineable: indeclinable

**Comment by funderburkjim** [comment]
> Should not we?  

Yes, I did mark those 3 'incorr.' as abbreviations.
