### ISSUE TITLE
abnormending 2 letter ending errors

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/csl-corrections#34]
GiMR:YAT

Should be GiR

See https://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/servepdf.php?dict=YAT&key=GiMR

**Comment by drdhaval2785** [comment]
KAditaMr:PW
KAditar is correct
https://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/servepdf.php?dict=PW&key=KAditaMr

**Comment by drdhaval2785** [comment]
bo:IEG
boqiyA ?
https://www.sanskrit-lexicon.uni-koeln.de/scans/IEGScan/2014/web/webtc/indexcaller.php?key=bo&input=slp1&output=SktDevaUnicode

**Comment by drdhaval2785** [comment]
IEG
diestruck is an English word
Need some markup change.
https://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/servepdf.php?dict=IEG&key=diestruck

**Comment by drdhaval2785** [comment]
atitfH:PD
atitfh
https://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/servepdf.php?dict=PD&key=atitfH

**Comment by drdhaval2785** [comment]
sie:LAN
sic
https://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/servepdf.php?dict=LAN&key=sie

**Comment by drdhaval2785** [comment]
Salmall:VEI
Salmali (Note the change from शल्मल्ल् - शल्मलि)
https://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/servepdf.php?dict=VEI&key=Salmall

**Comment by drdhaval2785** [comment]
kuheqo:VCP
kuheqI
https://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/servepdf.php?dict=VCP&key=kuheqo

**Comment by drdhaval2785** [comment]
budDism:PE
buddhism
https://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/servepdf.php?dict=PE&key=budDism

Debatable whether to retain English word buddhism or convert to slp1 budDism?

**Comment by drdhaval2785** [comment]
devAsuravinirmAtr:INM
devAsuravinirmAtf
https://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/servepdf.php?dict=INM&key=devAsuravinirmAtr

It is a print change. dot transposed between t and r in the scan.

**Comment by drdhaval2785** [comment]
SvASvH:SKD
SvASvaH
https://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/servepdf.php?dict=SKD&key=SvASvH

**Comment by drdhaval2785** [comment]
karRAww:VCP
karRAwwa
https://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/servepdf.php?dict=VCP&key=karRAww

**Comment by gasyoun** [comment]
> abnormending 2 letter ending errors

Batch headword corrections back again!

**Comment by drdhaval2785** [comment]
https://github.com/sanskrit-lexicon/csl-corrections/issues/34#issuecomment-755463127
https://github.com/sanskrit-lexicon/csl-corrections/issues/34#issuecomment-755470641
https://github.com/sanskrit-lexicon/csl-corrections/issues/34#issue-780734812

These three items are pending. 
Rest corrections made in csl-orig repository via https://github.com/sanskrit-lexicon/csl-orig/commit/c0411e07e7347d38a83ad57fdd24b84fae8711d7 commit.

**Comment by drdhaval2785** [comment]
#68, #69, #70 noted.
Closing this issue, as rest have already been handled.

**Comment by funderburkjim** [comment]
Beware! This issue first wave of Dhaval tsunami :)
