### ISSUE TITLE
AE English Corrections

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-corrections#42]
Sampada is working on the corrections from
https://github.com/sanskrit-lexicon/CORRECTIONS/blob/master/english_error/output/ae_error.txt.

**Comment by gasyoun** [comment]
It seems errors will be hunted in 5 years from now and will be a rare bird.

**Comment by sanskritisampada** [comment]
Done Jim...!

**Comment by funderburkjim** [comment]
<details><summary>Sampada's corrections</summary>
<pre>
1492:carte:blanche:OK
2398:crepuscle:scular:OK
2414:crinigerous:romopama:OK
2698:demand:deside:decide
;scan error
; jim:  This is an abbreviation for 'desiderative':
;   The common abbreviation (as yet unmarked in ae.txt) is 'desid.'
; So I changed line to:
; <div n="lb"/>desid. ({#jijYAsate#}), ‘d. ed his name’
3231:drone:dronish:OK
4520:glad:dening:OK
4953:hocus:pocus:OK
6067:latch:postern:OK
6193:lie:liest:OK
6904:mote:seest:OK
7226:obit:uary:OK
7690:pass:throughts
7879:pest:ilence:OK
7916:phlegm:phlegmagogue:OK
8805:remove:geneology:genealogy
;scan error
9884:stick:ubt:Doubt
;vague scan
10041:suit:eble:able
10520:transcend:ental:OK
10608:trolly:ey:OK
10989:verb:osity:OK
</pre>
</details>

Only one comment -  Posting two print changes  (under 'demand; abd 'remove' )
