### ISSUE TITLE
ap90 english word corrections, take 2

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-corrections#48]
@sanskritisampada  is working on the corrections from
https://github.com/sanskrit-lexicon/CORRECTIONS/blob/master/english_error/output/ap90_error.txt.

About 300 items there.

We're using a variant of the 'CAE' process 1 method, with 
 a temporary repository https://github.com/sanskrit-lexicon/temp_corrections_ap90.

**Comment by gasyoun** [comment]
> We're using a variant of the 'CAE' process 1 method, with
a temporary repository https://github.com/sanskrit-lexicon/temp_corrections_ap90.

Understood.

**Comment by funderburkjim** [comment]
Corrections done.  See revised https://github.com/sanskrit-lexicon/CORRECTIONS/blob/master/english_error/output/ap90_error.txt.


50+ print changes also noted in https://github.com/sanskrit-lexicon/csl-corrections/blob/master/dictionaries/ap90/ap90_printchange.txt
