### ISSUE TITLE
install corrections, 1

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-corrections#5]
This comment starts a way to communicate that changes are done.  Rather than Dhaval
and I sending email notifications, we can just paste the correction commit messages as
comments in this issue.  That way,  
* we'll get email notifications automatically, from the Github message
* Other people who might at some time want to be aware of corrections can also
   see what is updated
* It will provide some history, that can be examined.

Any comments on this?  If it seems a good thing, I'll add it to the instructions in #2.

**Comment by funderburkjim** [comment]
Installed: pwg:35439,droRa; 19764,kram; 101905,SreyaMs (print change); 102723,sa; 102722,sa

**Comment by drdhaval2785** [comment]
Sure. This seems OK. May be updated in instructions.

**Comment by funderburkjim** [comment]
installed: ccs: 5038,kup;11126,DI 

Also, a submitted correction for yat marked as processed, with 'not enough information"

**Comment by funderburkjim** [comment]
installed stc: 15705, prez; 24206,sva; 12787, paYcama;20894,saMskf

Note 1:  the paYcama example was `5(me.) -> 5{^me^}. `   In stc,  `{^X^}` represents that X is in a superscript.   Looking for `(me` elsewhere in stc resulted in about 20 similar corrections.

Note 2: Caujolle (who submitted these corrections) made the following enhancement suggestion:
```
 "cf." is not referenced (or maybe the abbreviations are not yet referenced in this dictionary, 
a pity as this one is more complete and reliable than the Burnouf one 
(one can notice it has three authors (with Renou who is famous for his sanskrit grammar also) 
and is more recent, that explain why)
```

Adding abbreviations to stc would not be particularly hard, and could be done with a text editor
by a careful person.

**Comment by funderburkjim** [comment]
installed bur: 11471, pracodayāmi

Will do rest of bur later today or tomorrow -- Posted work done since I'm taking a break and want
to avoid syncing problem if Dhaval is working early.

**Comment by drdhaval2785** [comment]
Corrected
mw:262545;234227;68463;162924;161686;86231.1;62541;197590;173266;239967 

Trying to regenerate MW on cologne server, but it seems to be taking a lot of time. Maybe this is the largest dictionary, and will take some time to regenerate all the intermediates.

**Comment by drdhaval2785** [comment]
vcp:26789 installed.

**Comment by gasyoun** [comment]
> Adding abbreviations to stc would not be particularly hard, and could be done with a text editor
by a careful person.

is Caujolle interested in it?

**Comment by drdhaval2785** [comment]
SKD and VCP corrections installed.

**Comment by drdhaval2785** [comment]
WIL corrections installed.

**Comment by drdhaval2785** [comment]
AP90 corrections installed.

**Comment by drdhaval2785** [comment]
PW corrections installed.

**Comment by funderburkjim** [comment]
installed bur: 11462,pracinomi; 8975, hw=devana; 6629,cit; 6914, Cettf; 2281,ABAs; 18758,sumuK; 9883,niraYjana;17449,saDa;2763,ugra; 13181,mahezvara


Many of these required marking abbreviations previously missed;  e.g. capitalized abbreviations such
as `<ab>Cf.</ab>`.   
All in all, 4000+ lines changes for bur in csl-orig.
Also revised burab_input.txt (in csl-pywork).

**Comment by drdhaval2785** [comment]
Does this significant change to BUR make it to history.txt? As far as I understand, history.txt tracked generic changes in a dictionary.

**Comment by drdhaval2785** [comment]
Installations done. Closing the thread.
A few which survived require closer examination / generic changes.

**Comment by gasyoun** [comment]
> Does this significant change to BUR make it to history.txt? As far as I understand, history.txt tracked generic changes in a dictionary.

Would love to know as well, @funderburkjim

**Comment by funderburkjim** [comment]
> is Caujolle interested in it?

I did ask her, in email.

**Comment by funderburkjim** [comment]
> history.txt

Before our new regime for corrections,  I usually added notes summarizing changes.
For instance, after our catch-up work on user-submitted corrections, I probably would have added
notes such as
```
Dec 22, 2019  Corrections from Correction Form (~100) for submissions from July -current.
Dec 22, 2019  BUR. Marked many abbreviations starting with capital letters.
   Ref: https://github.com/sanskrit-lexicon/csl-corrections/issues/5#issuecomment-568121482
```
The second comment would be noting 'a significant change to BUR', while the first would be
emphasizing that we had 'caught up' with a backlog of user-corrections.

I'm not sure what role, if any, history.txt should have now. 
Should history.txt be considered obsolete?
Should the above two comments be added to history.txt?  
Only the BUR comment?  

What do others think?

**Comment by funderburkjim** [comment]
> AP90 corrections installed.

Why not the lnums and/or headwords such as
``` 
installed stc: 15705, prez; 24206,sva; 12787, paYcama;20894,saMskf
```

**Comment by drdhaval2785** [comment]
@funderburkjim 

Re `why not lnums and hw`

https://github.com/sanskrit-lexicon/csl-corrections/commits/master git logs contain the full details. So for this issue, remained terse.

**Comment by gasyoun** [comment]
> Should history.txt be considered obsolete?

What are the scenarios of it's use, Jim, as you envision it?

> Should the above two comments be added to history.txt?
Makes sense, if the file makes sense at all.

> What do others think?

I think we should have a tag or abbreviation for a drastic change. Like NB (nota bene) like that last huge BUR update - it's not just many, it's literally thousands of changes.

**Comment by funderburkjim** [comment]
Added the Burnouf changes to history.txt.
With a reference to the note above.

Such 'major' changes, seem worth a mention in history.txt.  For instance, the 1200 Vartt. changes
made today in mw has been added.
