### ISSUE TITLE
gst english corrections

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-corrections#50]
@sanskritisampada beginning english word corrections for GST dictionary (Goldstucker).

Based on Dhaval's list: [gst_error.txt](https://github.com/sanskrit-lexicon/CORRECTIONS/blob/master/english_error/output/gst_error.txt)

**Comment by sanskritisampada** [comment]
Hi Jim
Pushed GST corrections to github.
Regards

**Comment by funderburkjim** [comment]
Got it!  Am beginning review.

**Comment by funderburkjim** [comment]
Am reviewing using this Github display, which shows the diffs of your commit:

https://github.com/sanskrit-lexicon/temp_corrections_acc/commit/40ad25f08ebeba35f322b203b9bb4bbefca77759

**Comment by funderburkjim** [comment]
@sanskritisampada 

Made a couple of comments/changes in two commits:

* [ref1](https://github.com/sanskrit-lexicon/temp_corrections_acc/commit/0e3f4c064c43d9d4aa29d51555030cc402866cc8)
* [ref2](https://github.com/sanskrit-lexicon/temp_corrections_acc/commit/a7c498ced541b8ccc94aa3f569a8ac102e49bd39)

I'll have to deal with that scan-page mismatch (under 6756: aByArohaRIya) in a different place.

Review now finished.  Good work!

WIll begin installation of corrections.

**Comment by funderburkjim** [comment]
Revised [gst_error.txt](https://github.com/sanskrit-lexicon/CORRECTIONS/blob/master/english_error/output/gst_error.txt)

**Comment by gasyoun** [comment]
> Pushed GST corrections to github.

I give you my thanks.

**Comment by sanskritisampada** [comment]
Thanks Jim. Noted your inputs.

**Comment by funderburkjim** [comment]
gst scanned image problem solve.  Ref: https://github.com/sanskrit-lexicon-scans/gst/issues/1

Also solved at cologne in scans/GSTScan/2014/web/pdfpages directory.

**Comment by funderburkjim** [comment]
Incidentally, even though the current displays for gst are in scans/GSTScan/2020/,
the current location at cologne of scans for gst is scans/GSTScan/2014/...

the 'dictinfo.php' file (in csl-websanlexicon) and csl-apidev  give locations of scanned images.

**Comment by gasyoun** [comment]
> the current location at cologne of scans for gst is scans/GSTScan/2014/

Maybe time to unite?

**Comment by funderburkjim** [comment]
The virtue of leaving the scans in 2014 is that then the old displays still work, as well as the new displays.

The total size of scans is probably on  order of 10GB, based on this estimate from 2014:
```
ACC:web/pdfpages:110MB
MW72:web/pdfpages:181
AE:web/pdfpages:146
GST:web/pdfpages:39
STC:web/pdfpages:90
BOP:web/pdfpages:29
YAT:web/pdfpages:91
BOR:web/pdfpages:67
KRM:web/pdfpages:536
CCS:web/pdfpages:140
VCP:web/pdfpages:543
AP:web/pdfpages:371
SHS:web/pdfpages:602
MWE:web/pdfpages:331
GRA:web/pdfpages:110
BEN:web/pdfpages:66
SNP:web/pdfpages:29
CAE:web/pdfpages:89
PW:web/pdfpages:612
MD:web/pdfpages:141
PUI:web/pdfpages:83
MCI:web/pdfpages:399
PWG:web/pdfpages:1546
BUR:web/pdfpages:94
WIL:web/pdfpages:336
SCH:web/pdfpages:62
INM:web/pdfpages:161
MW:web/pdfpages:488
SKD:web/pdfpages:503
AP90:web/pdfpages:334
IEG:web/pdfpages:22
PD:web/pdfpages:855
PE:web/pdfpages:52
BHS:web/pdfpages:73
VEI:web/pdfpages:73
PGN:web/pdfpages:19
tots:web/pdfpages:9423
```

(ref at Cologne: scans/awork/misc/space/)

We have about 100GB at Cologne, AFAIK. Thus not advisable to make a copy of the images
somewhere else at Cologne.
