### ISSUE TITLE
IEG, English word corrections

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-corrections#51]
Sampada has done corrections for IEG based on Dhaval's [IEG suspect english words](https://github.com/sanskrit-lexicon/CORRECTIONS/tree/master/english_error/output).

Now working on installation.

**Comment by funderburkjim** [comment]
New [ieg_error.txt](https://github.com/sanskrit-lexicon/CORRECTIONS/blob/master/english_error/output/ieg_error.txt)

Interestingly,  almost all the many changes were errors in the scan.  This suggests:
1) Thomas' original proofreading of digitizations worked well for IEG.
2) The IEG text itself was not so well proofread.

**Comment by funderburkjim** [comment]
Corrections now installed.

79 print changes also posted to [ieg_printchanges.txt](https://github.com/sanskrit-lexicon/csl-corrections/blob/master/dictionaries/ieg/ieg_printchange.txt)

**Comment by gasyoun** [comment]
> Good on @sanskritisampada for checking the scanned images so thoroughly!

Thanks to @sanskritisampada and @funderburkjim , 79 print is a lot.
