### ISSUE TITLE
BOR English word corrections

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-corrections#53]
@sanskritisampada 

sanskrit-lexicon/temp_corrections/temp_corrections_ae  now prepared for Borooah english word
corrections.  (Borooah English-Sanskrit Dictionary)

Please pull temp_corrections_ae  and use bor_error.txt and bor.txt -- same procedure as for ieg, etc.

**Comment by sanskritisampada** [comment]
Thanks Jim....Pulled and task has begun!

**Comment by funderburkjim** [comment]
These corrections now made by @sanskritisampada  and installed by @funderburkjim .

169 lines changed in bor.txt.

Refer:  
* [bor_error.txt](https://github.com/sanskrit-lexicon/CORRECTIONS/blob/master/english_error/output/bor_error.txt)
* [bor_printchange.txt](https://github.com/sanskrit-lexicon/csl-corrections/blob/master/dictionaries/bor/bor_printchange.txt)  91 cases.

**Comment by funderburkjim** [comment]
@sanskritisampada noticed one repeated problem (about 20 times):
`<tch> wrongly written as <kS>`

This was likely caused by a bug in one of the programs I used to transform the data
from its original form provided by Thomas to its current form.
