### ISSUE TITLE
MCI English word errors

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-corrections#57]
Review possible errors in English words in Mahabharata Cultural Index,
as produced by [mci_error.txt](https://github.com/sanskrit-lexicon/CORRECTIONS/blob/master/english_error/output/mci_error.txt)

**Comment by funderburkjim** [comment]
Prepared mci for @sanskritisampada in [temp_corrections_acc](https://github.com/sanskrit-lexicon/temp_corrections_acc) repository.

**Comment by funderburkjim** [comment]
196 cases reviewed and installed.

136 print changes (refer [mci_printchange.txt](https://github.com/sanskrit-lexicon/csl-corrections/blob/master/dictionaries/mci/mci_printchange.txt)).

@sanskritisampada   Thank you!

**Comment by gasyoun** [comment]
> 136 print changes (refer mci_printchange.txt).

Nowadays a book 10 times smaller has 5 times more mistakes, how well made. Thanks @sanskritisampada
