### ISSUE TITLE
MD English error, 2nd pass

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-corrections#59]
We've already been through English errors once several months ago with MacDonell.

This work examines latest suggested corrections [md_error.txt](https://github.com/sanskrit-lexicon/CORRECTIONS/blob/master/english_error/output/md_error.txt) prepared by Dhaval.

This review looks to have a few additional cases to correct, although most suggestions
will probably be 'OK' for one reason or another.

**Comment by funderburkjim** [comment]
Copies of md.txt and md_error.txt (adjusted to have just one suggestion per line)
are in temporary repository:  https://github.com/sanskrit-lexicon/temp_corrections_ap90

These are ready for @sanskritisampada to pull, process, and push.

**Comment by funderburkjim** [comment]
Note to self:

I have not yet processed Sampada's corrections to MCI.

**Comment by gasyoun** [comment]
> This review looks to have a few additional cases to correct, although most suggestions
will probably be 'OK' for one reason or another.

Oh, ok.

**Comment by funderburkjim** [comment]
@sanskritisampada has done the md corrections.  Still for me to install.

**Comment by funderburkjim** [comment]
Corrections installed.

31 lines changed.
No print changes to report.

@sanskritisampada Now finished with this round of 'md' corrections.
My few notes now in [md_error.txt](https://github.com/sanskrit-lexicon/CORRECTIONS/blob/master/english_error/output/md_error.txt).

**Comment by gasyoun** [comment]
> Now finished with this round of 'md' corrections.

Do you have a list or table to track who is there next on the list or off the list?

**Comment by funderburkjim** [comment]
I am going alphabetically down the list of xx_error.txt files in https://github.com/sanskrit-lexicon/CORRECTIONS/tree/master/english_error/output.

**Comment by gasyoun** [comment]
> alphabetically down the list of xx_error.txt files

So half way, but big ones ahead. And English errors will not help in German dictionaries. Remember you had the old orthography libraries running for PWK and PWG?

![fdfdsfsdfsdfds](https://user-images.githubusercontent.com/80761/113628407-87454e80-966d-11eb-9935-ecb0c2cc12f9.JPG)

**Comment by funderburkjim** [comment]
For the German dictionaries, we first would need to have someone fluent in German.
@sanskritisampada also knows French, but not German, I think.

Since @drdhaval2785 is generating the xxx_error.txt files using, I think, Pyenchant,
he could also do a similar generation for the German dictionaries  (and for the French).

However, for the German dictionaries, there is an additional difficulty dealing with systematic
differences between the German language at the time of Bohtlingk and the current German
language.

**Comment by gasyoun** [comment]
> he could also do a similar generation for the German dictionaries (and for the French).

@drdhaval2785 can you? Jim forgot he did it 2014 already https://github.com/sanskrit-lexicon/CORRECTIONS/issues/18

> German dictionaries, there is an additional difficulty dealing with systematic
differences between the German language at the time of Bohtlingk and the current German
language.

No, it's not an issue. If the `Pyenchant` will do it's part, I will start the German reading and will find a German to continue it.

**Comment by sanskritisampada** [comment]
I can definitely do for the French.
My German is not good enough for these corrections.
