### ISSUE TITLE
mw72 english word error

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-corrections#60]
This work examines latest suggested corrections [mw72_error.txt](https://github.com/sanskrit-lexicon/CORRECTIONS/blob/master/english_error/output/mw72_error.txt) prepared by Dhaval.   This is Monier-Williams Sanskrit-English dictionary of 1872.

Copies of mw72.txt and mw72_error.txt (adjusted to have just one suggestion per line)
are in temporary repository:  https://github.com/sanskrit-lexicon/temp_corrections_ap90

These are ready for @sanskritisampada to pull, process, and push.

This is a rather large list - about 900 (after putting one word per line.

**Comment by funderburkjim** [comment]
@sanskritisampada finished her work on mw72.

Now for me to review and install.

**Comment by gasyoun** [comment]
> rather large list - about 900

Sure it's a big one for manual checking and updating.

**Comment by funderburkjim** [comment]
Corrections now installed.  See also [csl-orig/v02/mw72.txt](https://github.com/sanskrit-lexicon/csl-orig/commit/b5f1be1255b726adc13aac89f50b59490ecaf55f#diff-e866cced453748f06698c22def78d25328b72552826e80df0c9086dfc58ae698).

39 of the 379 corrections identified as print changes [See:](https://github.com/sanskrit-lexicon/csl-corrections/commit/d1883d80f361a2defdc88962d601724212a42928#diff-863642c8004f223b13e2df2c40b729bfd15accd9a5aab7a9948b5cfb4f1577cf)

Interesting that so many typos were found, relatively few print changes.

Thanks @sanskritisampada !

**Comment by gasyoun** [comment]
> Interesting that so many typos were found, relatively few print changes

Agree. Long live @sanskritisampada and @funderburkjim !
