### ISSUE TITLE
SHS English word errors

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-corrections#64]
This work examines latest suggested corrections shs_error.txt prepared by Dhaval. This 'dictionary' is  *Shabda-Sagara Sanskrit-English Dictionary*.

Copies of shs.txt and shs_error.txt (adjusted to have just one suggestion per line)
are in temporary repository: https://github.com/sanskrit-lexicon/temp_corrections_ap90

These are ready for @sanskritisampada to pull, process, and push.

There are about 1300 items to examine.

**Comment by Andhrabharati** [comment]
This info may be of some use-

Sabdasagara is just a print of 3rd ed. of Wilson's Dictionary, with the title changed for some undocumented reasons.

So comparing SHS and WIL could help identifying the errors in both.

**Comment by funderburkjim** [comment]
@Andhrabharati   Yes. Was aware of the similarity, but appreciate the reminder.  Have used Wilson numerous times in
this exercise to correct the many print mistakes of SHS.

Incidentally, found a few (very few) instances where SHS adds information to Wilson; but have not kept track of these.

**Comment by funderburkjim** [comment]
see [shs_error.txt](https://github.com/sanskrit-lexicon/CORRECTIONS/blob/master/english_error/output/shs_error.txt) for the changes made.  

Sampada has finished her part.  I have reviewed and am in process of installing corrections.

**Comment by Andhrabharati** [comment]
> Incidentally, found a few (very few) instances where SHS adds information to Wilson; but have not kept track of these.

You might've compared with the Wilson 2nd ed., not the 3rd ed.

**Comment by funderburkjim** [comment]
Yes, according to our [front matter](https://www.sanskrit-lexicon.uni-koeln.de/scans/csldev/csldoc/build/dictionaries/prefaces/wilpref/wilpref01.html),  the Cologne digitization of Wilson is from the 2nd edition.

**Comment by funderburkjim** [comment]
About 940 corrections.  And 830+ of these were classified as print changes.


This marathon now finished!
@sanskritisampada Thank you!
