### ISSUE TITLE
armh underscore and hyphen in key1

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-corrections#65]
@drdhaval2785  There are several headwords in [armh.txt](https://raw.githubusercontent.com/sanskrit-lexicon/csl-orig/master/v02/armh/armh.txt) with 
unexpected characters `_` or `-` in 'k1' field.  What is significance?

'k1' field is expected to have only SLP1 characters.  May '_' and '-' be removed in 'k1' ?

**Comment by drdhaval2785** [comment]
I knew that this question would come. 

The underscore denotes genitive relation. E.g. indra_raTa would mean Indra's chariot.


Will remove it. But it will require some time, as I am fully occupied in covid pandemic managent in my district.

**Comment by gasyoun** [comment]
> underscore denotes genitive relation

So we could leave it in the metadata, not to delete it totally?

**Comment by drdhaval2785** [comment]
Will keep in key2 and remove from key1.

**Comment by drdhaval2785** [comment]
https://github.com/sanskrit-lexicon/csl-orig/commit/8ea2e8eb9ef8dc7b9302b19fef29e4cd18eb10b0 removed all non-alphabetic items from key1.
Works well in my localhost.
Should work well when rerun on Cologne servers.
If @funderburkjim thinks it fit, ARMH should actually be put on the homepage along with SKD and VCP.

**Comment by funderburkjim** [comment]
armh revisions now installed at Cologne.

**Comment by funderburkjim** [comment]
Revised csl-homepage to include ARMH.
