### ISSUE TITLE
WIL English word corrections

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-corrections#66]
This work examines latest suggested corrections wil_error.txt prepared by Dhaval. This is  *Wilson's Sanskrit-English dictionary (2nd edition)*.

Copies of wil.txt and wil_error.txt (adjusted to have just one suggestion per line)
are in temporary repository: https://github.com/sanskrit-lexicon/temp_corrections_ap90

These are ready for @sanskritisampada to pull, process, and push.

There are 650+ items to examine.

**Comment by gasyoun** [comment]
> There are 650+ items to examine.

A big list. The book itself can barely be held in one hand.

**Comment by sanskritisampada** [comment]
Thanks Jim.
On it!


Sampada

**Comment by funderburkjim** [comment]
Corrections finished by @sanskritisampada and installed by me.
See commit 76243a1, link above.

**Comment by funderburkjim** [comment]
Also see [wil_error.txt](https://github.com/sanskrit-lexicon/CORRECTIONS/blob/master/english_error/output/wil_error.txt)

**Comment by funderburkjim** [comment]
About 300+ changes.
157 print changes (See [wil_printchange.txt](https://github.com/sanskrit-lexicon/csl-corrections/blob/master/dictionaries/wil/wil_printchange.txt)).
