### ISSUE TITLE
VEI english word corrections

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-corrections#67]
This work examines latest suggested corrections vei_error.txt prepared by Dhaval. This is  *The Vedic Index of Names and Subjects*.

Copies of vei.txt and vei_error.txt (adjusted to have just one suggestion per line)
are in temporary repository: https://github.com/sanskrit-lexicon/temp_corrections_ae

These are ready for @sanskritisampada to pull, process, and push.

There are about 150 items to examine.

**Comment by funderburkjim** [comment]
@sanskritisampada has finished examination.

## help requested
There is one that we need help on:

See https://sanskrit-lexicon.uni-koeln.de/simple/vei/AsaNgaplAyogi/slp1

The question is in Footnote 2, where we see `Dyā-dvi. eda gives the tale at length in Vedic`.

What is 'eda' ?   Is it just 'veda'? 

Here is scan:

![image](https://user-images.githubusercontent.com/6393033/124394024-725b7400-dccb-11eb-9881-fd75b550e726.png)

**Comment by Andhrabharati** [comment]
Does this help you?-

![image](https://user-images.githubusercontent.com/75209130/124394676-1c63ec00-dd1e-11eb-91ba-30c45be54898.png)

[In many occassions, I see that Koeln scans are bad.]

**Comment by gasyoun** [comment]
> I see that Koeln scans are bad

Yours is easy to read indeed.

**Comment by Andhrabharati** [comment]
I collect all available copies of books and scans (for our works), irrespective of duplications!!

**Comment by funderburkjim** [comment]
@Andhrabharati  --  Yes indeed.  That shows the result clearly.  Thanks!

**Comment by funderburkjim** [comment]
corrections installed (including the 'help wanted one').

36 print changes also posted to [vei_printchanges.txt](https://github.com/sanskrit-lexicon/csl-corrections/commit/db7f8de315c424af334b569e228bc9bc03c7cc4d)
