### ISSUE TITLE
Commit confusion

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-corrections#7]
I started off today's work by examining the repository at Cologne and at Github.
```
cologne:  git log: latest commit 660c072074  Dec 20 21:29   pw:5211 ...
github :  Latest commit bfc2fba pw 2 cases pending  (1 parent 660c072)
```

At cologne, the git log has no mention of commit bfc2fba .

At github, here is the bfc2fba commit:   https://github.com/sanskrit-lexicon/csl-corrections/commit/bfc2fba6cd6fc59ae39831a74873e6f1e5d416ce

It says that bfc2fba   has 1 parent 660c072  (660c072 is latest commit at Cologne)

QUESTION:
Where did bfc2fba   commit on github come from?   

GUESS:  It was pushed from Dhaval's local installation.

Experiment:  at Cologne,  'git pull origin master'.
This succeeds (thankful for that!).

So the guess was right.

I found this situation confusing.   

Suggestion:  Dhaval and Jim should aim to leave three things
in sync when they finish a session:
For all repositories (normally, csl-orig and csl-corrections) they change, the following should be the same:
1) Local installation
2) github
3) Cologne

Also, if corrections are made to dictionary xxx,  then on local installation and Cologne installation,
do the csl-pywork/v02   regeneration of the dictionary (so corrections will be reflected in displays).

**Comment by drdhaval2785** [comment]
I apologize. 
I will be careful now onwards to keep csl-orig and csl-corrections in sync in local, github and cologne at end of the session.

**Comment by gasyoun** [comment]
> leave three things in sync

To be added to documentation.
