### ISSUE TITLE
औ in Lanman - question

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/csl-corrections#71]
Is it a random occurrence?
Does Lanman write all औ as āu?
'au' is much more common way of writing औ।

```
<L>1665<pc>160-b<k1>QOk<k2>QOk
{@√ḍhāuk@}¦ ({@ḍhaúkate; ḍuḍhauké; ḍhaukitá;@} <lbinfo n="ḍhauk-itá;"/>
{@ḍhaukáyati@}). approach; {%<ab>caus.</ab>%} bring
near.
<div n="p"/>{@+ upa,@} bring to; provide.
<LEND>
```

**Comment by Andhrabharati** [comment]
@drdhaval2785 
A quick look at the print shows he did mark all ḍhauk as ḍhāuk under this entry, if not anywhere else.

![image](https://user-images.githubusercontent.com/75209130/132295569-39c772a4-79bd-4df5-954f-7399ff99e019.png)

Cologne digitisation has marked only the HW as such, but not its other forms in brackets)!

Probably he might have taken (mistaken ?, the regular root being ḍhauk) it as a similar one like dhā (धा), or probably he might have noticed in some v.l. forms in some work (commentaries ?).

**This can initiate a new task of compiling a v.l. list for all धातुs listed in all schools of Skt. grammar.**
@gasyoun any takers for this task from your 'dhatu' batch?

As I have posted elsewhere in the group, Dr. Palsule did compile the list of धातुs in various schools, but skipped some v.l. forms in commentaries.
[incidentally this post of mine has received **no responses** yet!]

**Comment by drdhaval2785** [comment]
```
$ cat lan/lan.txt | grep 'āu'
{@√ḍhāuk@}¦ ({@ḍhaúkate; ḍuḍhauké; ḍhaukitá;@} <lbinfo n="ḍhauk-itá;"/>
```
So, it seems to be a single error.

**Comment by gasyoun** [comment]
> Does Lanman write all औ as āu?

It's Whitney way, so must stay as is.

**Comment by Andhrabharati** [comment]
American style?

in quite many ways American works differ with European works!!

**Comment by gasyoun** [comment]
> American style?

You can say that. 

![whitney](https://user-images.githubusercontent.com/80761/132573068-63010244-ade6-4741-812e-2dea46b32371.png)

Emeneau follows him.

**Comment by funderburkjim** [comment]
There are actually several other 'āu' instances in the original digitization from Thomas.
https://raw.githubusercontent.com/funderburkjim/lanman/master/orig0/lsr0.txt

Search for 'a1u', which is the AS encoding of the original. ( in 215 lines).
Might check if any of these are handled improperly in the Lanman dictionary.

This transcoder file is relevant - https://github.com/funderburkjim/lanman/blob/master/orig/refs/as_romanuni2.xml
It accounts for the conversion from  'āu'' to 'au' which.

**Comment by Andhrabharati** [comment]
Would you mind giving the original file links for all digitisations @funderburkjim? (or may host them at the Github repo)

These seem to be having proper data wrt the books. One should not lose them.
