### ISSUE TITLE
metr. abbreviation in MW

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-corrections#74]
Noticed 9 instances of abbreviation 'metr.' in mw.txt.
Here are the headwords and lines involved:
```
; <L>97951<pc>502,2<k1>druh<k2>druh<h>1<e>1
329893 old <hom>1.</hom> <s>druh</s> ¦ <ab>cl.</ab> 4. <ab>P.</ab> <s>dru/hyati</s> 
(<ab>ep.</ab> and metr. also <ab>Ā.</ab> <s>°te</s>), <ls>Br.</ls>; <ls>MBh.</ls>; <ls>R.
</ls> &c. ...... ETC.
;
; <L>101150<pc>516,1<k1>DArmiReya<k2>DArmiReya<e>2
340507 old <s>DArmiReya</s> ¦ metr. <ab>fr.</ab> <s>DarmiRI</s> <ab>g.</ab> 
<s>SuBrA<srs/>di</s>.
;
; <L>177247<pc>876,3<k1>rADeya<k2>rADeya<e>2
593936 old <s>rADeya</s> ¦ <lex>m.</lex> metr. of <s1 slp1="karRa">Karṇa</s1> 
(<ab>cf.</ab> under <s>rADA</s>), <ls>MBh.</ls>; <ls>R.</ls>; <ls>Rājat.</ls><info lex="m"/>
;
; <L>191177<pc>942,1<k1>vAmneya<k2>vAmneya<e>2
638899 old <s>vAmneya</s> ¦ <lex>m.</lex> metr. <ab>fr.</ab> <ab>prec.</ab> 
<ls>PañcavBr.</ls><info lex="m"/>
;
; NOTE:  'prec.' is this preceding entry:
; <L>191176<pc>942,1<k1>vAmnI<k2>vAmnI<e>1
; <s>vAmnI</s> ¦ <lex>f.</lex> <ab>N.</ab> of a woman (<ab>cf.</ab> next). <info lex="f"/>

; <L>196841<pc>969,2<k1>vinatAtanayA<k2>vi/-natA—tanayA<e>3
657508 old <s>vi/-natA—tanayA</s> ¦ <lex>f.</lex> 
‘daughter of <ab n="Veda" slp1="veda">V°</ab>’,
 metr. of <s1 slp1="su-mati">Su-mati</s1>, <ls>VP.</ls><info lex="f"/>
;
;  NOTE:  'daughter of Veda' should be corrected to 'daughter of vinatA'

; <L>220979<pc>1089,2<k1>SEkzita<k2>SEkzita<e>1
736204 old <s>SEkzita</s> ¦ <lex>m.</lex> metr. <ab>fr.</ab> <s>SikzitA</s>, 
<ls>Pāṇ. 4-1, 113</ls> <ab>Sch.</ab><info lex="m"/>
;
; <L>252391<pc>1247,3<k1>sEMhika<k2>sEMhika<e>2B
840139 old <s>sEMhika</s> ¦ <lex>m.</lex> (<ab>fr.</ab> <s>siMhikA</s>), 
metr. of <s1 slp1="rAhu">Rāhu</s1> or the personified ascending node 
(<ab>cf.</ab> next), <ls>L.</ls><info lex="m"/>
;
; <L>252394<pc>1247,3<k1>sEMhikeya<k2>sEMhikeya<e>2B
840148 old ¦ metr. of <s1 slp1="rAhu">Rāhu</s1> (<ab>cf.</ab> <ab>prec.</ab>), 
<ls>Kāv.</ls>; <ls>VarBṛS.</ls>; <ls>BhP.</ls><info lex="inh"/>
;
; <L>255999<pc>1266,1<k1>sTOrya<k2>sTOrya<e>2
851699 old <s>sTOrya</s> ¦ <lex>m.</lex> metr. <ab>fr.</ab> <s>sTUrA</s> 
<ab>g.</ab> <s>gargA<srs/>di</s>.<info lex="m"/>
;
```

These need to be marked as abbreviation, but there seem to be two distinct usages:
* metr. = metronymic  (same as matronymic) "a name derived from that of the mother or a maternal ancestor"
  * DArmiReya, rADeya, vAmneya, vinatAtanayA, sEMhika, sEMhikeya, 
* metr. = ?   (NOT sure of abbreviation meaning here)
  * druh , SEkzita,  sTOrya

## Questions:
1. Do you agree with the 'metronymic' tooltip for those words mentioned?
2. What should the tooltip be for the other 3 ?
3.

**Comment by Andhrabharati** [comment]
MW has (ep. and metr. also Ā. °te) under **druh**, as against " ep. auch med." in PWG.
So it appears the **metr.** is an error in MW for P. (Parasmaipada), looking at the "**med.**" in PWG.

The other two cases also belong to the same category as the rest (metronymic).

**Comment by gasyoun** [comment]
> Do you agree with the 'metronymic' tooltip for those words mentioned?

Yes.

**Comment by Andhrabharati** [comment]
@funderburkjim 

it seems you had missed my above post reg. **druh** entry.
I suggest that it be taken as a print change [**metr.** for **med.** (german)], and change it to the corresp. Skt. word **P.** (Parasmaipada).

@gasyoun 
do you have anything against this?

**Comment by funderburkjim** [comment]
Nice analysis re 'druh'.  Additionally noticed mw72 has `also Ā.`

This issue now completed.

**Comment by gasyoun** [comment]
> do you have anything against this?

@Andhrabharati I'm all for it
