### ISSUE TITLE
YAT ?? case

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/csl-corrections#76]
There is a case in YAT which is marked with ?? .
The mark is known as jihvAmUlIya.
page - https://www.sanskrit-lexicon.uni-koeln.de/scans/csl-apidev/servepdf.php?dict=YAT&page=308-b

Digitization -
```
 <L>15828<pc>308-b<k1>jihvAmUlIya<k2>jihvA-mUlIya
 {#jihvA-mUlIya#}¦ {#(yaH)#} 1. {%m.%} The mark
<>for {%visarga%} {??}.
 <LEND>
```

jihvAmUlIya is represented by 'Z' in SLP1 according to www.sanskrit-lexicon.uni-koeln.de/talkMay2008/SLP1.pdf .

So made the following change.
```
-<>for {%visarga%} {??}.
+<>for {%visarga%} {#Z#}.
```

**Comment by drdhaval2785** [comment]
I am not sure whether the transcoder code renders jihvAmUlIya properly or not.
If not, @funderburkjim may have to write a few lines of code to accomodate it.

**Comment by drdhaval2785** [comment]
Correction made in csl-orig. 
transcoding portion pending for Jim.

**Comment by Andhrabharati** [comment]
> 
> 
> I am not sure whether the transcoder code renders jihvAmUlIya properly or not.
> If not, @funderburkjim may have to write a few lines of code to accomodate it.

This is what Jim gave under PWG #5 (to be from slp1_deva.xml, which is used for rendering purpose), 

`< Z =  jihvamuliya = h with line below`
`< V =  upadhmaniya = h with breve below`
-->
`<e> <s>INIT,SKT</s> <in>Z</in> <out>\u1cf2</out> <next>INIT</next></e>`
`<e> <s>INIT,SKT</s> <in>V</in> <out>\u1cf2</out> <next>INIT</next></e>`

> transcoding portion pending for Jim.

So apparently Jim is ready with the transcoding.

Unicode has thus-
1CF2 ᳲ VEDIC SIGN ARDHAVISARGA = vaidika jihvaamuuliiya upadhmaaniiya
1CF3 ᳳ VEDIC SIGN ROTATED ARDHAVISARGA

I would just like to say that quite many olden Skt. texts that I saw have this 1CF3 character for upadhmAnIya, not the iCF2 character.

However LIES (p. 202) gives the same 1CF2 character for both jihvamuliya & upadhmaniya, which is the base for Cologne's (Jim's) working.

**Comment by funderburkjim** [comment]
Should V be changed to 1CF3?

**Comment by Andhrabharati** [comment]
I see it thus in some old Telugu and Kannada books!

**Comment by drdhaval2785** [comment]
Similar 
https://archive.org/details/in.ernet.dli.2015.326738/page/n103/mode/2up
https://archive.org/details/Siddhantakaumudi_English_Translation_SR_Ray/1.SiddhantakaumudiVol1Part1-Sandhi-SrRay1926/page/n165/mode/2up
https://archive.org/details/in.ernet.dli.2015.496388/page/n229/mode/2up
https://archive.org/details/in.ernet.dli.2015.424393/page/1613/mode/1up

Therefore, many old publications have them printed similarly.
So, let us not change it as of now.

**Comment by Andhrabharati** [comment]
So probably it is marked the otherway more in South Indian editions, than in Northern India!!
