### ISSUE TITLE
MW regeneration fails

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/csl-corrections#8]
@funderburkjim 
I updated mw.txt on cologne and tried to regenrate MW displays.
But the program ran for eternity without any results. It kind of hanged every time. Therefore, changes made in MW are not carried to the displays. Can you regenerate MW?

**Comment by funderburkjim** [comment]
I see that the MW displays are still ok at Cologne.

Where does it hang? -

**Comment by funderburkjim** [comment]
Just leave it for now -- I'll look at problem tomorrow after the skype conference.

**Comment by drdhaval2785** [comment]
Hangs before xml generation.

**Comment by funderburkjim** [comment]
This is a thorny problem, which I think is peculiar just to mw and just to Cologne.
Regeneration of mw locally caused no problems.

I just regenerated mw at Cologne, and it looks ok (displays work).
Here's what I did.

By trial and error, I happened to find that make_xml.py did NOT hang when run with python3 on
Cologne for mw.  But did usually (but not always) hang when run with python (= python2 at Cologne.)
So in csl-pywork, I added the ability in generate.py to detect if the generation was occurring at
Cologne.  Then I made two scripts use python3 (when generation is occurring for mw at Cologne):
redo_xml.sh  and mwkeys/redo.sh.  
The reason for mwkeys/redo.sh change is that I got a similar hanging (and eventual 'getötet' (killed) message) from one of the python programs in mwkeys/redo.sh, when that program was run in python2.   I also had to change mwkeys/extract_keys_b.py  in the part that uses 'maketrans' -- reason was that several parts of the code have to be different between python2 and python3.

Again, to reiterate, the regeneration of MW does seem to work at Cologne  (and also under python2 local installation).

BUT the reason for failure is still unclear.   My guess at the moment is that there is some server limit (in cpu time or cpu memory)  that we are exceeding when python2 is used for MW at Cologne.  Whereas, somehow python3 is slightly more efficient and does not exceed whatever those limits are.
I tried rebuilding another large dictionary (PWG) at Cologne, with python and had no problems. Just to reiterate, the code generation is exactly as it was before for
* all dictionaries EXCEPT mw at Cologne
* all dictionaries, including mw, for non-Cologne installations.

Question for @drdhaval2785 Is maketrans used anywhere else but in mwkeys/extract_keys_b.py ?

**Comment by drdhaval2785** [comment]
I do not think that maketrans or sorted with cmp is used anywhere else. Because I regenerated all dicts for local usage by py3. No errors reported except this program.

**Comment by funderburkjim** [comment]
>  regenerated all dicts for local usage by py3

Good. It seems likely that our code now runs, and gives same results, in both python2 and python3.

**Comment by gasyoun** [comment]
> some server limit (in cpu time or cpu memory) that we are exceeding when python2 is used for MW at Cologne

MW kills even Linux. How can a human brain handle it?

**Comment by drdhaval2785** [comment]
@funderburkjim 
If there is no issue on Cologne regeneration, we can close this issue.

**Comment by funderburkjim** [comment]
Agree on close
