### ISSUE TITLE
BHS English word corrections

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-corrections#80]
We deal with the list of possible English word errors in bhs.txt (Buddhist Hybrid Sanskrit Dictionary).
The list is provided in
[bhs_error.txt at commit 7b27d61e4d](https://github.com/sanskrit-lexicon/CORRECTIONS/commit/7b27d61e4d5e88463738d1eab04ad33cccdd9dc6).

**Comment by funderburkjim** [comment]
bhs_error.txt is too large (4075 items) to examine each individually.

Work was done (see above commit) to separate the list into 2 parts:
* bhs_error_ok.txt 3895   Assume these don't need to be examined now.
* bhs_error_todo.txt 180 .  This is the list to examine individually.

@sanskritisampada will examine the todo list.

**Comment by funderburkjim** [comment]
@sanskritisampada finished.

Corrections installed  (see above commit to csl-orig)

70 print changes also noted (see above commit to this repository).

i's dotted and t's crossed.

**Comment by gasyoun** [comment]
> bhs_error_ok.txt 3895 Assume these don't need to be examined now.

So all done?

**Comment by funderburkjim** [comment]
Yes, this task is considered done. -- Those 3895 'error_ok' cases are believed to be non-English.

**Comment by gasyoun** [comment]
> 3895 'error_ok' cases are believed to be non-English.

Should we mark them as such in the code?

**Comment by funderburkjim** [comment]
As I recall, many are Tibetan words, as the text indicates.  
Someone versed in the specialty of this dictionary might benefit from adding markup.
I don't think we should undertake such markup in the foreseeable future.

**Comment by gasyoun** [comment]
> such markup in the foreseeable future.

At least we would not try to treat them as English words in the future, using AI approaches.
