### ISSUE TITLE
change git remote

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-corrections#83]
This is perhaps the only cdsl repository where it is convenient to **push** to github from the cologne server.
However, for quite some time, a push fails with message which reads in part:
`remote: Support for password authentication was removed on August 13, 2021.`

With Bing Chat's help, I found that this problem can be solved by changing the remote on the cologne server.
```
git remote -v
origin  https://github.com/sanskrit-lexicon/csl-corrections.git (fetch)
origin  https://github.com/sanskrit-lexicon/csl-corrections.git (push)

git remote set-url origin git@github.com:sanskrit-lexicon/csl-corrections.git
# check
git remote -v
origin  git@github.com:sanskrit-lexicon/csl-corrections.git (fetch)
origin  git@github.com:sanskrit-lexicon/csl-corrections.git (push)
```
Now pushes work.   

WHY?  Not sure why authentication works with the new remote url.

On local computer,  the remote is of the https variety `https://github.com/...`, but still pushes
work, at least within the git for windows terminal.

**Comment by gasyoun** [comment]
Other than @funderburkjim only @drdhaval2785 knows the magic?

**Comment by drdhaval2785** [comment]
I am not sure whether I know it fully well though.

**Comment by drdhaval2785** [comment]
Now I can claim that I know some things about how to use git on Cologne servers.
