### ISSUE TITLE
User Corrections - Dhaval

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-corrections#84]
I've got caught up with user-submitted corrections to csl-orig.
The readme_howto.txt gives some idea of my procedure.
Unfortunately, it is rather complicated.

@drdhaval2785   I am passing this responsibility over to you.  You probably will develop your own way of processing user corrections.  Suggest you give it a try in a couple of weeks. Of course, I'll provide further explanations as needed.

**Comment by drdhaval2785** [comment]
I will try to do this after a couple of weeks

**Comment by drdhaval2785** [comment]
I have given it a try and have been able to complete the 7 user corrections submitted during past two days.
I have regenerated, confirmed on Cologne and also sent email to the submitter.
I have not found any issue in the process, and hence I am now confident that I will be able to take over this responsibility from @funderburkjim .

**Comment by funderburkjim** [comment]
Glad to see that you tackled this.   Changes to mw seem fully done at Cologne.

The only thing I noticed was that mw72 and shs were not updated on cologne server.
I pulled csl-orig on cologne server, and remade  mw72 and shs in csl-pywork/v02.

I'll comment separately on the hwnorm1c  question you raised.
