### ISSUE TITLE
Some user corrections skipped entering the cdsl texts

### ISSUE THREAD

**Issue by Andhrabharati** [sanskrit-lexicon/csl-corrections#89]
Found the cfr file containing the user corrections submitted.

Though a good number of them have the "corrected" remark at the end of the submission, seen that some of those were not carried into the cdsl text files.

**Comment by Andhrabharati** [comment]
I was looking at MW feedback in 2023, and noticed the above.

**Comment by funderburkjim** [comment]
Probable oversights made by me in processing 2023 user corrections.  
Missed corrections need to be processed. 
Not sure how to identify the ones needing attention.
One possible approach:  
* @Andhrabharati  provides a list of csl-orig issue numbers that need attention.  
* @funderburkjim to finish the installation of these corrections.

**Comment by Andhrabharati** [comment]
@funderburkjim 

I did a redo of the exercise I did two days ago (in my file), now (in cdsl file) [using the cfr file].

Here are the three entries that got skipped--
[As I did not go the csl-orig issue way, I cannot give those numbers that you've asked.]

- 12/15/2023 21:15:58	MW	ID=184900	vajra—danta	boor	boar	Typo	erik.seldeslachts@gmail.com:01-12-2024 corrected
- 12/19/2023 13:21:46	MW	dadrūṇa	dadrūṇa	(also dara°).	(also dard°).	Typo	srhodes@snowcrest.net:01-14-2024 corrected
- 12/19/2023 13:34:20	MW	89885.1	dadru	(also dara°	(also dard° 	Typo (I am fairly certain that this is a misprint based on the other variations listed below).	srhodes@snowcrest.net:01-14-2024 corrected

Also, it is seen that some of the entries reported by @aumsanskrit as hierarchy errors, that were marked as "Unable to reproduce" (or "Not able to reproduce"), are **in fact quite valid**.
The issue lies in the <e> number of those entries which decides the List display [**which I think Scott is using**] ordering.
In most of the cases, it is `<e>2` for `<e>1` in the cdsl text.

**Comment by funderburkjim** [comment]
@Andhrabharati   I think these have now been handled (and the above commit will also show the changes).

My notes: [temp_hierarchy.txt](https://github.com/sanskrit-lexicon/csl-corrections/files/15339584/temp_hierarchy.txt)

**Comment by Andhrabharati** [comment]
Good to note the same, @funderburkjim.

BTW, I see that the commit contains a correction--
`<L>226089` is a `<e>1` entry only, not `<e>2` type.

![image](https://github.com/sanskrit-lexicon/csl-corrections/assets/75209130/586427de-2b28-48a0-972c-ed34ea88949e)

Note the Devanagari text in this; and this also is a grouped HWs entry, having **saṃ-varta** & **saṃ-var°taka** as HWs.
[In my (revision) working I had marked quite a huge number of such grouped entries; probably they would find place in the cdsl text sometime, as in GRA.]

**Comment by funderburkjim** [comment]
`<L>226089 is now  <e>1` in cdsl.
